src/db/users.js
I was receiving this error:
```
SequelizeValidationError: notNull Violation: role cannot be null
```
because the sign-up api route doesn't set a value for the role yet is required by the DB model
=> fixes new user sign-up flow, which wasn't setting a default role value

webpack/webpack.config.dev-client.js, webpack/webpack.config.dev-server.js, webpack/webpack.config.prod.js
Hey @davelandry,
Here's a first try at implementing what you suggested in #40.
Our (datachile) use case is creating a separate virtualhost for hosting static assets. That hostname would be defined as the envvar `CANON_CONST_ASSETS_HOSTS` .
=> Make environment vars CANON_CONST_* available as globals

src/client.jsx
I'm 98.74% sure that this fixes the checksum mismatch issue. Works with canon app, also with Datachile (`npm link`ed canon into datachile)
I'd appreciate a review, test, merge and release.
Thanks.
=> Fixes #66 — Resources need to be loaded at init() time.

README.md, db/testTable.js, locales/en/datawheel-canon.json, locales/es/datawheel-canon.json, package-lock.json, package.json, src/auth/auth.js, src/auth/social.js, src/components/Forms.css, src/components/Login.jsx, src/db/users.js, src/images/linkedin-logo.svg
Last but not least, this PR adds the elements needed for CNY to integrate with LinkedIn OAuth infrastructure:
* Adds the LinkedIn passport module (passport-linkedin-oauth2)
* Updates DB table structure to reference LinkedIn
* Adds placeholder localization strings
* Adds basic LinkedIn button and css (see note below)
* Adds Github logo
* Basic setup instructions
@davelandry as usual, I threw in some placeholder CSS and as always feel free to take a look over and make any edits 😄
=> LinkedIn OAuth Integration

src/components/Login.jsx, src/components/SignUp.jsx, src/components/SocialButtons.jsx
Adds a component (SocialButtons) to unify social sharing buttons for login and signup components so that new services will only need to add the buttons in one place. 
(Currently only Twitter and Facebook are in the signup form as I hadn't realized they needed to be added to both places, but instead of copying and pasting thought this might be helpful)
=> Reusable component for social login button

src/components/Login.jsx, src/components/SignUp.jsx
It looks like I caused a bug in the social buttons components due to the module import path. It would work when testing within canon but when trying to use the components outside of canon from another project the import path gave errors. These changes appear to fix that.
=> Hotfixes social buttons import path for external projects

README.md, src/auth/social.js
This PR allows sites with users logging in from Google, Facebook, LinkedIn, Github or Twitter, to request sharing of user e-mail addresses.
=> Request emails for social logins

README.md, src/components/Reset.jsx
Currently canon tries to use browserHistory to redirect users after a successful password change which unfortunately doesn't work. This is a proposed fix for redirecting users after successful password change (#91).
_NB_: This PR would introduce a _**breaking**_ change for users embedding the `Reset` component, and would require passing a prop for `router` instead of `location` (see updated docs).
=> fix for reset redirect after password change #91

packages/vizbuilder/src/helpers/chartconfig.js
closes #174 
Considering the @frabarz PR #173 I used `members[timeDrilldownName].length` for to check the length of available years.
=> removes plots when there is 1 member in timeDimension

packages/vizbuilder/src/helpers/chartconfig.js, packages/vizbuilder/src/helpers/sorting.js
This solves a problem when selecting a measure whose cube has a time dimension level not named "Year", like the "Adults With Serious Mental Illness" measure.
=> [vizbuilder] Time dimension validation bug

packages/vizbuilder/src/helpers/chartconfig.js, packages/vizbuilder/src/helpers/formatting.js, packages/vizbuilder/src/helpers/query.js
this puts the combinations queries first and then the more simple ones
=> [vizbuilder] inverts chart order

packages/vizbuilder/src/helpers/chartconfig.js, packages/vizbuilder/src/helpers/loadstate.js, packages/vizbuilder/src/index.js
There's a bug I didn't notice where expanding a combined chart makes all charts disappear, with no option to go back. This solves it.
=> [vizbuilder] fix activechart rendering issue

packages/vizbuilder/src/helpers/chartconfig.js
=> [vizbuilder] removes stacked charts if the aggregation type is "median" in vizbuilder

packages/cms/src/components/Viz/PercentageBar.jsx
The new PercentageBar component was improperly inheriting `dataFormat` from its parent config. This PR fixes that bugged inheritance.
=> fixes dataformat bug in percentagebar

packages/cms/src/formatter/FormatterEditor.jsx
Missing leading slash in FormatterEditor was causing api gets in the formatter tab to fail, this (one-character) PR fixes that.
=> fixes bug with loading formatters by adding leading slash to api call

packages/cms/src/Builder.jsx
The ability to "seed" a database via a model is not yet part of canon. The eventual plan will be for canon to fill the `formatter` table using `seed` content from the model, but this is not yet implemented.
As a stop-gap, it was temporarily decided that formatters in the CMS would load from a bundled js file. However, this means that when a current user of canon uses the CMS, adding new formatters to the db has no effect.
This PR changes it back to the original functionality: Load the formatters from the DB.  Note that this will cause NEW installations of the canon cms to have an empty array of formatters, and they will need to be added to the DB manually, until the `seed` functionality is added to canon.
=> [cms] changes formatter get from localjs to db

packages/cms/src/db/profile_stat.js, packages/cms/src/db/topic_stat.js
Closes #276 to allow for tooltips longer than 255 characters.
=> changes tooltip type from varchar to text, closes #276

packages/cms/src/components/cards/GeneratorCard.jsx, packages/cms/src/components/cards/VisualizationCard.jsx, packages/cms/src/components/editors/GeneratorEditor.jsx, packages/cms/src/components/editors/SimpleVisualizationEditor.jsx, packages/cms/src/profile/ProfileEditor.jsx, packages/cms/src/profile/TopicEditor.jsx
This PR performs a `urlSwap` on the API paths for simple editors for generators and visualizations.
For generators, this is only important in terms of fetching the payload for the "preview." When users type `/api?id=<id>` into the `API` section of a generator and Fetch that data, I need to pre-process that url and swap `<id>` with whatever the user is currently previewing in the CMS, so the payload comes back accurately.  For good measure, this actually uses the FULL `urlSwap`, so the user is free to use any other variable between brackets that they wish to use (e.g. `&name=<name>`).
For the ez viz builder, this is actually much more complex.  It's simple enough to swap in the `<id>` and other vars in the API URL when the user clicks fetch (just as before, with generators). However, …
=> adds <id> url swap to both gen and viz simple editors

packages/cms/src/components/editors/GeneratorEditor.jsx, packages/cms/src/components/editors/SimpleGeneratorEditor.jsx, packages/cms/src/formatter/FormatterEditor.jsx
I accidentally removed an `else` that caused Materializers not to render. This fixes that reversion.  
Also fixes a bug in formatters that was causing the formatter page to not retrieve the list properly.
Also puts in a "camelify" method to generators so the suggested keys get camelCased and have no spaces in them.
=> fixes materalizer and formatter bugs, and camelifies keynames in ez-mode generator

packages/cms/src/story/StoryEditor.jsx, packages/cms/src/story/StoryTopicEditor.jsx
We recently reworked the way that text cards work, in order to accommodate #239.  However, this change was not propagated to the stories, causing a red screen.  This updates stories to use the new format.
=> fixes bug with stories invoking old version of textcards, prevents red screen on stories page

packages/cms/src/components/editors/GeneratorEditor.jsx
The ace window wouldn't render without a payload, this is a hotfix for that behavior.
=> hotfixes ace rendering problem with payloads

packages/cms/src/components/editors/SimpleGeneratorEditor.jsx
Simple mode was breaking for searches on the `search` table because it uses `results` instead of `data`.  This handles that case.
=> adds  to possible payload returns for search results

packages/cms/app/pages/Bar.jsx, packages/cms/app/routes.jsx, packages/cms/src/components/Viz/PercentageBar.css, packages/cms/src/components/Viz/PercentageBar.jsx
This adds a `showPercent` switch to the data config for perc bars so I can properly render one of the charts for CDC
=> changes render behavior for perc bar for a cdc chart

packages/cms/src/utils/varSwapRecursive.js
Apologies for the confusing branch name - the issue number refers to an issue in `cdc-pha`, not here.
This PR adds support for multiselect to the topic endpoint.
=> adds support for multiselect to topic endpoint

packages/cms/package-lock.json, packages/cms/src/api/formatters.js, packages/cms/src/utils/varSwapRecursive.js
changes formatter and varSwapRecursive js interactions to transpile js before transmitting it to the client for IE support.
=> fixes ie bug by transpiling all client js

packages/cms/src/api/mortarRoute.js, packages/cms/src/components/Viz/PercentageBar.jsx
Adds transpiling to the stories endpoint so visualizations render on ie.
Also backpacking on this PR is a change to percentage bar that uses innerHTML in the title to preserve formatting.
=> adds transpiling for stories

packages/cms/src/api/formatters.js, packages/cms/src/api/mortarRoute.js
When compiling formatters, they may be malformed.  These runtime errors can bring down entire sites. This PR wraps all formatter logic in try/catch to prevent this.
Note that this must take place in TWO places:
1) In `/api/formatters`, we use `buble` to transpile the code to ES5 for the front-end. 
2) On the actual server-side formatter logic (when the application hits `/api/variables..` for example), when the code gets "turned into real functions" by `formatters4eval`.
This catches errors in both locations. 
Closes #418
=> wraps formatters in try-catch to avoid js crashes

packages/logiclayer/src/api/logiclayer.js
This bug was discovered adding custom `properties` with logiclayer. 
To solve it, I changed `hierarchy` by `level`, because the property is related with the Level instead of the Hierarchy. 
We didn't have the issue in DataUSA because the hierarchy name was the same with the level name. (Example: `University`)
=> fixes bug using properties with logiclayer

packages/cms/src/api/cmsRoute.js, packages/cms/src/api/searchRoute.js, packages/cms/src/components/Search/Search.jsx, packages/cms/src/db/profile.js, packages/cms/src/profile/ProfileBuilder.jsx
This closes #468 by adding hierarchy (levels) to profiles.  The search endpoint now has a `?levels=Comma,Separated,Levels` option to filter your results by level.  This filtering is done implicitly in the CMS - if you are on a given profile, the search bar will only return levels that are appropriate for the currently open profile.
**IMPORTANT NOTE**: This includes a breaking database change (adds the `levels` column to the `profile` table).  When deployed on existing installs, this column will need to be created.
=> [cms] Issue 468 - adds profile levels/hierarchy

bin/server.js, packages/cms/src/components/cards/VisualizationCard.jsx, packages/cms/src/utils/varSwapRecursive.js
This PR addresses a few problems:
1) The babel transpiler for ES6->ES5 (for IE) was not wrapped in a try catch. This caused a red screen as soon as you typed a breaking letter into a viz in the CMS
2) Expanding on the problem above, typing letters in the CMS **should not** be making live render changes to the viz underneath. This was likely causing perf problems. We now only render the viz when the window is not open (i.e., the user has pressed save to close the window)
3) There was no "is empty" check for the `seed` functionality in server.js, which was adding a brand new set of stock formatters on *every run*.  We now check to see that a table is empty before seeding it with data.
=> fixes bug in cms viz render and model seeding

packages/cms/src/api/mortarRoute.js
This patch removes the hard-coded datausa lookup table in `urlSwap` and instead uses the levels of the selected profile to look up an associated `attr`.  
Note: Still need to revisit this so that the front-end urlSwap works, see issue #494 for details.
=> fixes attr lookup to properly retrieve for urlswap

packages/cms/src/components/cards/SelectorCard.jsx, packages/cms/src/profile/TopicEditor.jsx
@cnavarreteliz requested that Selector titles be translatable. This already works by using a variable in `{{brackets}}` due to `varSwarRecursive`, however it still rendered poorly on the front of the card.  This PR fixes that.
Also, There was a hard-coded english language reference still in the codebase. This has been changed to the generic `localeDefault`.
=> fixes selector to render variable in title card, fixes hard coded english language bug

packages/cms/app/pages/Profile.jsx, packages/cms/src/Builder.jsx, packages/cms/src/api/cmsRoute.js, packages/cms/src/api/mortarRoute.js, packages/cms/src/components/Profile.jsx, packages/cms/src/components/Viz/index.jsx, packages/cms/src/components/cards/GeneratorCard.jsx, packages/cms/src/components/cards/SelectorCard.jsx, packages/cms/src/components/cards/TextCard.jsx, packages/cms/src/components/cards/VisualizationCard.jsx, packages/cms/src/components/editors/GeneratorEditor.jsx, packages/cms/src/components/editors/TextEditor.jsx, packages/cms/src/profile/ProfileBuilder.jsx, packages/cms/src/profile/ProfileEditor.jsx, packages/cms/src/profile/TopicEditor.jsx, packages/cms/src/story/StoryBuilder.jsx, packages/cms/src/utils/funcifyFormatterByLocale.js
This PR closes #494 by:
- adding a search `attr` data object to the front end for use by `urlSwap`, allowing generators to use syntax like `hierarchy=<hierarchy>` (and any other variable from the search table).
- allowing the use of `locale` in formatters.
=> Add formatter locale

packages/cms/src/utils/varSwapRecursive.js
in varSwapRecursive, I was making the assumption that if the object i've encountered is an array, it is sufficient to recursively run varSwapRecursive on it again.
However, profiles now have `levels`, which is simply an array of strings. Therefore, I was trying to run varSwapRecursive on a __string__, which was casting it to an object and breaking the datatype.
I added a case into the "array" part of the function.  As it fans over the array, if it is an object, we use varSwapRecursive, but if it's a string, we have "hit bottom" and can use the new `strSwap`.
Fixes a bug that @cnavarreteliz discovered in Estonia with hierarchies.
=> fixes bug in varSwapRecursive that caused levels to improperly turn into objects

packages/cms/src/api/mortarRoute.js
The `attr` object that is fetched from the search table is not a db row - it's a big giant sequelize response object. This was messing up the `urlSwap` function and causing it to use lots of unnecessary and broken key/values, which, among other problems, was failing to swap the `hierarchy` key for estonia.
Fix: Convert the attr response to raw json before passing it to the swap object.
=> fixes bug with search attr not properly replacing in urlswap

packages/cms/src/utils/stats.js
While porting code for the standard morbidity ratio from the original SAS a few extra lines were included that aren't related to the actual SMR calculation and end up throwing off the calculation.
=> fixes bug in SMR calculation port from SAS

packages/cms/package-lock.json, packages/cms/package.json, packages/cms/src/api/cmsRoute.js, packages/cms/src/cache/cubeData.js
Adds support for tesseract-client to Canon CMS.
In this PR, the cms no longer improperly borrows `CANON_LOGICLAYER_CUBE` as a way to designate where mondrian lives.  Users should now use `CANON_CMS_CUBES` to designate a mondrian or tesseract endpoint.
NOTE: `CANON_CMS_CUBES` originally expected a path like `path.com/cubes`, because it was used for fetching cube metadata.  From now on, `CANON_CMS_CUBES` should be set only to the actual path for mondrian or tesseract, (`path.com`), because I add the `/cubes` to fetch metadata in the appropriate place.
=> Add tesseract client

src/helpers/fixChars.js
Causing issues in Pantheon when trying to do URL param replacements with integer, since this function expects strings and will explode otherwise.
=> coerces variables to strings before attempting regex

packages/cms/package-lock.json, packages/cms/package.json, packages/cms/src/Builder.jsx, packages/cms/src/cache/cubeData.js
@cnavarreteliz Pointed out a bug in the cms path routing - if the Builder is put on a non-index route (as it almost always is, at `/admin` or `/builder`), then the pathing for permalinks was not being created correctly, and clicking profiles kicked you out to the IndexRoute.
This fix uses `props.location` to build a proper url for cms permalinks.
=> Fix cms permalink routing

packages/cms/src/profile/ProfileBuilder.jsx
@davelandry this is the bug observed in the CDC Demo that required a "jiggering" of the generator to clear the error state.
When I added "piecemeal updating" to generators, the `Object.assign` that I used for incoming new variables was failing to clear the `error` key that existed in state, therefore generators still appeared to be in error, even when the Preview id was updated.
=> Fix busted generator assign

packages/cms/src/api/mortarRoute.js
@cnavarreteliz Found a bug while working on OEC where generators that share an API only executed one of the generators. This was due to a bug in my de-duplication reducer logic, fixed in this PR.
=> fixes bug where duplicate apis only executed a single generator

bin/server.js
We recently updated `canon-cms` to be able to accept the `variables` object as a `POST` payload - This allows pages to be re-rendered WITHOUT re-running generators.
However, the default limit in express for posting json is 100kb.  This PR bumps that up to 50mb (note to @davelandry - this is needed for CDC, and likely datausa too).
Let me know if you would prefer this be a CANON var - I didn't want to overload the number of configuration variables.
=> [canon] increases json limit for post objects

packages/cms/src/components/Viz/Viz.jsx
A bug in config assignment breaks when multiple vizes are on a page, overloading the `defaultConfig` object and breaking vizes.  Assigning it to an empty object fixes this.
=> fixes bug in viz assign

packages/cms/src/components/sections/components/Selector.jsx
Blueprint 3 changed the way `renderItem` worked, but this missed (by me!) for the bp3 upgrade, resulting in blanks in multiselect dropdowns.  This fixes that bug.
=> updates multiselect to bp3, was missed in canon upgrade

packages/cms/scripts/migration/canon-cms-migrate-0.1.js
Updates migration-0.1 script to use James' new "Grouping" type instead of the now deprecated "Section," so migrated databases will properly make use of Groupings and its DOM compliance.
=> [cms] Updates Migration Script to use Grouping type

packages/cms/scripts/migration/canon-cms-migrate-legacy.js
I recently updated the 0.1 migration script to use the new "Grouping" and "Hero" types but forgot to do the same for the legacy script.
This PR also properly splits up the Hero and About sections as they should look in Datausa.
=> updates legacy script to new Section Types

packages/cms/src/components/cards/TextCard.jsx
Single language-mode was shipping a busted `false` language content to the db.  This fixes that bug.
=> fixes bug with editing textcards in single lang

packages/cms/src/components/Viz/Viz.css, packages/cms/src/components/Viz/Viz.jsx, packages/cms/src/components/sections/Default.jsx, packages/cms/src/components/sections/Grouping.jsx, packages/cms/src/components/sections/Hero.jsx, packages/cms/src/components/sections/InfoCard.jsx, packages/cms/src/components/sections/MultiColumn.jsx, packages/cms/src/components/sections/SingleColumn.jsx, packages/cms/src/components/sections/Tabs.jsx
Hides visualization titles unless a `title` is explicitly defined in the viz config; closes #619
=> hide visualization titles

packages/cms/src/components/Viz/PercentageBar.jsx
In certain situations (usually a bad `dataFormat` function) a user could pass `undefined` values into the data array for PercentageBar.  Attempts to access properties of these values results in a red screen, both on the CMS and front end. 
This PR adds a filter to the viz that ensures a given data value exists before attempting to graph it.
This is a followup to https://github.com/DeloitteGeospatial/cdc-pha/issues/955
=> prunes data for nulls in percbar

packages/cms/src/utils/formatters/stripHTML.js
the striphtml function does not work if a number is passed to it (or anything non-string, for that matter).
Cast the input to string before running `.replace`.
=> adds str conversion to striphtml

packages/cms/src/components/Viz/Viz.jsx, packages/cms/src/components/sections/Default.jsx, packages/cms/src/components/sections/Grouping.jsx, packages/cms/src/components/sections/Hero.jsx, packages/cms/src/components/sections/InfoCard.jsx, packages/cms/src/components/sections/MultiColumn.jsx, packages/cms/src/components/sections/SingleColumn.jsx, packages/cms/src/components/sections/Tabs.jsx
closes #692 
[related issue](https://github.com/Datawheel/canon/blob/feature-multisearch/packages/cms/src/components/Viz/Options.jsx#L26-L28)
=> passes section title to Options.jsx & restores filename fallbacks

packages/cms/src/api/mortarRoute.js
Fixes a bug discovered by @alexandersimoes that caused any profile slug in a URL, other than the first one, to fail its id lookup.
=> fixes bug with secondary slug lookups

packages/cms/src/member/MetaEditor.jsx
Sometimes search members have no slugs. This causes a crash on filtering in MetaEditor, fixed in this PR.
=> Fix crash on Meta Editor when Members have no slugs

packages/cms/src/member/MetaEditor.jsx
Fixes two small bugs Victor discovered while using the MetaEditor:
- `id` column wasn't sorting numerically (as they are technically strings)
- Upon choosing an image, all filters were erroneously reset.
=> fixes bugs with id sorting and filter being lost after save image

packages/cms/src/api/cmsRoute.js, packages/cms/src/api/searchRoute.js, packages/cms/src/components/Viz/Table.css, packages/cms/src/components/interface/Toolbox.css, packages/cms/src/member/MetaEditor.jsx
The MetaEditor Panel can be quite slow on initial load, because I was loading ALL search members and then filtering with javascript.
This PR moves the querying to the server using limiting, which results in a much quicker experience for navigating large member tables.
=> [cms] remote search for Meta Panel

packages/cms/src/api/imageRoute.js
closes #798
Image lookups will now attempt to find parents, if the `:parents` endpoint has been configured in tesseract.  Fails gracefully if it has not.
=> adds ability to search for parents in images

packages/cms/src/components/Viz/Table.css, packages/cms/src/components/Viz/Table.jsx, packages/cms/src/components/cards/VisualizationCard.css, packages/cms/src/components/fields/Button.css, packages/cms/src/member/MetaEditor.css, packages/cms/src/member/MetaEditor.jsx
Found out you can replace react-table's pagination controls with your own, so I replaced them with canon `Button`s (and did the same for the Meta table while I was at it). 
Tested and made sure the controls are in fact appearing when `showPagination` is set to `true` in viz config.
closes #783
=> table viz pagination style

packages/cms/src/components/editors/DimensionEditor.jsx
Handles the case where a cube has been changed beneath an existing configuration, so the user can successfully open and modify a dimension without crashing.
=> hotfixes bug when cube is changed underneath meta

packages/cms/src/actions/profiles.js, packages/cms/src/api/cmsRoute.js, packages/cms/src/profile/ProfileBuilder.jsx, packages/cms/src/reducers/status.js
Closes #821 
@davelandry The reason for the above issue was that I was populating the search table asynchronously. Therefore, the Profile came back as created before any search rows were inserted, and no preview was being auto-selected.  This caused the preview to be empty, and `<id>` to not work in our first generator.
There are a few ways to think of how to address this:
1) You need to click your own preview AFTER adding a dimension. This is what people usually do, they search for a sample member in the search, and by the time they do this, the search has populated (partially, at least).
2) We could switch to the "I only ever fetch variables if you press a manual button" school of thought.  This would refuse to run if you hadn't picked a preview, which would prevent the behavior above. …
=> makes search population blocking for #821

packages/cms/src/actions/profiles.js, packages/cms/src/api/cmsRoute.js, packages/cms/src/components/interface/Header.jsx, packages/cms/src/reducers/profiles.js, packages/cms/src/reducers/status.js
This PR adds the ability to duplicate profiles and sections.
When copying profiles, the entire tree is preserved.  If a section is copied from one profile to another, many of its variables may be `N/A` due to the fact that the target profile will not share generators. Additionally, if a section is copied to a new profile, it will lose all selectors (as selectors are profile-wide, and the target profile will not have the same selectors).
However, if a section is copied within the same profile, selectors will be preserved.
Closes #826
=> Duplication of Profiles and Sections

packages/cms/src/components/sections/components/Stat.jsx
This will allow us to scale down the font size long stat values and labels, which is needed for DataMéxico.
closes #852
=> adds length modifier classes to stat elements

packages/cms/src/components/cards/TextCard.jsx, packages/cms/src/components/editors/GeneratorEditor.jsx, packages/cms/src/components/interface/AllowedSelector.jsx, packages/cms/src/utils/varSwapRecursive.js
Adds ability to customize allowed field, so one can use selectors in them.
This means that if someone had a compound variable that relies on a selector, like `{{tradeFlow[[ieSelector]]}}`, one could also use the value of that compound variable as the `allowed` property of that stat/entity - Meaning you could hide or show a given stat based on the truthiness of this compound variable.
Closes #851
=> [cms] Add custom allowed field

packages/cms/src/actions/profiles.js, packages/cms/src/components/cards/GeneratorCard.css, packages/cms/src/components/cards/GeneratorCard.jsx, packages/cms/src/components/variables/ConsoleVariable.jsx, packages/cms/src/components/variables/VarTable.css, packages/cms/src/components/variables/VarTable.jsx, packages/cms/src/reducers/status.js
Catches duplicate variables, Closes #707
I also backpacked a few bug fixes into this PR:
- fixed a bug that caused some variables not to show when switching to multi-language mode (due to a problem with how `diffCounter` was incremented)
- Simplified logic that GeneratorCards use to determine when to update their display panel
- Combined accidental duplicate cases in profile reducer, causing gen/mat deletions to misbehave.
=> adds duplicate catcher

packages/cms/src/actions/profiles.js, packages/cms/src/api/mortarRoute.js, packages/cms/src/components/cards/GeneratorCard.jsx, packages/cms/src/components/cards/SelectorCard.jsx, packages/cms/src/components/interface/Navbar.jsx, packages/cms/src/components/interface/Toolbox.jsx, packages/cms/src/utils/mortarEval.js
closes #838 
Adds a permanent, automatic attribute generator to all profiles. It will automatically export the `id`, `dimension`, `hierarchy`, and `slug` of the currently selected preview.
Additionally (and importantly!), these attributes run BEFORE the generators. Users now have access to these keys via the normal `variables` object in the generators themselves, allowing for more complex behaviors in the code of the generators.
This PR also includes a few notes in it for a future refactor of managing previews, which I've moved to a new issue, #841
=> adds automatic attribute generator to profiles

packages/cms/src/api/cmsRoute.js, packages/cms/src/components/interface/Outline.jsx, packages/cms/src/reducers/profiles.js, packages/cms/src/reducers/stories.js
Closes #844 
Closes #846 
Closes #845 
Changes the way sections are re-ordered in the following ways:
- Inserting section after another one now works (no longer appends to end of list)
- Inserting a section after a Grouping section creates a new Grouping
- Swapping two Grouping Sections properly swaps all their children as well
- Disallows for swapping for both the Final Group in a profile, and also the final section of any given group. This avoids confusing situations where sections seem to jump around.
This is still not quite perfect. There are some edge cases that feel a little janky, so another design pass should be scheduled.
=> Fix section groupings

packages/cms/src/components/Viz/StatGroup.css, packages/cms/src/components/sections/Hero.jsx, packages/cms/src/components/sections/Section.jsx, packages/cms/src/components/sections/components/Subnav.jsx
Changes to subnav logic:
- If there are <2 groupings, each non-grouping section will be shown in the subnav
- If there are >2 groupings, only grouping sections will be shown in the subnav
- if there are <3 subnav items, the subnav will not be shown
Closes #861
=> Issue 861 flat section hierarchy bugs

packages/cms/README.md, packages/cms/src/api/mortarRoute.js
Adds `CANON_CMS_REQUESTS_PER_SECOND` to config, a pass-through to `requestsPerSecond` in [promise-throttle](https://www.npmjs.com/package/promise-throttle).  updated readme.
=> Add throttle config

packages/cms/src/api/cmsRoute.js, packages/cms/src/reducers/profiles.js
Cesar pointed out that, when duplicating a section, it is confusing for the duplicated section to append all the way to the end of the profile.
Duplicating a section now adds a duplicate directly after the source section.
Closes #876
=> adds duplicated section directly after source section

packages/cms/src/Builder.jsx, packages/cms/src/css/mixins.css
Note: applying `overscroll-behavior: contain;` to the body element was required. So I'm injecting the style to the body element from within the Builder component only.
=> prevents accidental back swipes

packages/cms/README.md, packages/cms/src/api/mortarRoute.js, packages/cms/src/components/ProfileRenderer.jsx
Adds a `user` object and a `userRole` boolean to the Attributes generator, for the hiding / showing of content for a logged in user.
Note: If you want to make new variables based off `user` or `userRole` (such as `isPro` or `isPremium`), you **must make them in Materializers**.  These are the only entities that are re-run AFTER page load when the user object is instantiated.
Closes #891
=> Issue 891 usergen

packages/cms/src/api/cmsRoute.js, packages/cms/src/components/cards/DimensionCard.jsx
Does not require a major version release.
Two primary changes here:
- As discovered via the `Metro Areas` bug in DM, we now crawl through *ALL* hierarchies and take the set union of the discovered levels before hitting the cube.
- Search ingest changed from a looping `await` to a bulk upsert, speeding up ingest by an order of magnitude. Due to limitations in the search table and in sequelize (namely, search table uses a composite key) we were unable to use the `bulkCreate` method, and instead generate and execute a raw SQL query with an `ON CONFLICT` clause. This is not ideal, but the speed gains are undeniable. 
**NOTE:** I'd request that users take a backup of their cms db before running the new ingests, and if possible, contact me directly to supervise new ingests so I can confirm …
=> Issue 905 searchfix

packages/cms/src/utils/d3plusPropify.js
closes #918 
The "no data url" case was actually already handled in Table.jsx from a previous fix, but the "user JS doesn't return an object at all" case was not.
This catches for that case, preventing white screen of death.
=> [cms] catches non-object return in viz configs

packages/cms/src/api/imageRoute.js, packages/cms/src/member/MetaEditor.jsx
Victor discovered a bug where images with the same member id were not showing different images, only the "first" one. This was because I hadn't worked the new `cubeName` uniqueness into the image hosting logic. This PR fixes that bug.
=> [cms] fixes bug with image hosting wires crossed

packages/cms/src/actions/profiles.js, packages/cms/src/components/Viz/Options.jsx, packages/cms/src/components/Viz/Table.jsx, packages/cms/src/components/Viz/Viz.jsx, packages/cms/src/components/cards/VisualizationCard.jsx, packages/cms/src/reducers/status.js, packages/cms/src/utils/d3plusPropify.js
Makes several improvements against whitescreen in the cms:
- wraps `cellFormat` and `dataFormat` in try/catch, so that "Correct Syntax but Run-time Error" passthrough functions don't crash the vizCards (and in turn, the CMS)
- Adds a `dataFormat` default to the errorStub, fixing a bug where the errorStub crashes the viz on the front-end.
- Properly makes use of a `fetchingVariables` state, which blocks vizes from rendering before variables are finished loading, preventing crashes where vizes attempted to use the (not yet loaded) variables right away.
=> [cms] Fix trycatch formats

packages/cms/src/api/searchRoute.js
For legacy dimension-based searches, put `NULL` zvalues at end of list instead of beginning.
=> pushes null z values to end of search result

packages/cms/src/components/Viz/Options.jsx
Closes #943 
When investigating Felipe's bug report, I realized two problems with the Options.jsx panel.
1) The comparison for detecting changes in the data props in `componentDidUpdate` was faulty. 
Firstly, comparing arrays in this manner will never be equal, and further, setting results naively to `data` was what was causing the bug in the first place (spread out characters of the datacall in the Table).
2) Additionally, the data fetch was being done in a `forEach` loop, and as each response returned, it was pushed onto a "loaded" array. This does not guarantee ordering, and because `dataFormat` operations depend on ordering, this would fail half the time. 
In general, we should arrange to do more testing in the coming weeks on the Options panel's view data function.
=> fixes bug with options panel

packages/cms/README.md, packages/cms/src/actions/profiles.js, packages/cms/src/api/mortarRoute.js, packages/cms/src/api/searchRoute.js, packages/cms/src/components/fields/PreviewSearch.jsx, packages/cms/src/utils/attify.js, packages/cms/src/utils/urlSwap.js
Closes #910 
Adds a `parents` object to the Attributes generator, allowing for subsequent generator API calls to make use of its contents.
Adds functionality and documentation for string-based object crawling in Generator APIs, e.g., `/api?hierarchy=<parents[0].value>`
Also adds locale-specific "name" to the Attributes generator.
Notes:
- The parents call currently takes up to 10 seconds. Because having the parents object is necessary for subsequent generators, parent fetching blocks all generators from running until this operation is complete. @MarcioPorto is looking into this at the cube level, but @alexandersimoes should be aware that upgrading OEC to a version of the CMS that has this PR in it will add to load times (until the parents endpoint is examined)
- @alexandersimoes You will …
=> [cms] Automatic Parents Lookup

packages/cms/README.md, packages/cms/app/helmet.js, packages/cms/src/Builder.jsx, packages/cms/src/actions/profiles.js, packages/cms/src/api/cmsRoute.js, packages/cms/src/api/mortarRoute.js, packages/cms/src/api/searchRoute.js, packages/cms/src/components/cards/DimensionCard.jsx, packages/cms/src/components/editors/DimensionEditor.jsx, packages/cms/src/components/fields/PreviewSearch.jsx, packages/cms/src/components/interface/Dropdown.jsx, packages/cms/src/components/interface/Navbar.jsx, packages/cms/src/components/interface/PreviewHeader.jsx, packages/cms/src/components/interface/Toolbox.jsx, packages/cms/src/profile/DimensionBuilder.css, packages/cms/src/profile/DimensionBuilder.jsx, packages/cms/src/utils/attify.js, packages/cms/src/utils/groupMeta.js
Adds Variants to Dimensions, allowing for one profile to make use of several dimension variants. For example, a Subnational profile may have several geo variants (from varying cubes) that are fed through the same generators and profile text.
Does not require any database changes, however, some abstract structural changes have been made worth noting.
Profiles have a `meta` component that was a strictly ordered list of dimensions - `geo/product` for example. To accommodate variants, MULTIPLE dimensions may exist at a single index. This means that your 0th index could be a list of subnational_jpn, subnational_chn, etc. Essentially, profile_meta is now two dimensional:
```
dimensions ------------------>
variants
|      0       1
|      0       1
V      0
```
A new method called `groupMeta` is …
=> Issue 956 profile variants

packages/cms/src/member/MetaEditor.jsx
Adding Variants to profiles was causing a whitescreen in the Metadata panel due to an outdated linkify function - fixes that bug.
=> fixes bug with metadatalinkify

packages/cms/src/components/cards/TextCard.jsx, packages/cms/src/components/interface/Navbar.jsx, packages/cms/src/profile/ProfileEditor.jsx
closes #972 
Makes use of the otherwise unused `label` property of a profile to give CMS users a vanity plate for a given profile (instead of the first variant's slug).
=> adds profile label option

packages/cms/src/api/searchRoute.js, packages/cms/src/utils/populateSearch.js
closes #968 
Fixes entity sorting in the "nothing typed yet" autofill of the search panel.
Also required me to fix zvalues - we now normalize them on the fly (in this empty-search case) to avoid needing a new db column to store them.
=> fixes sorting and normalizes on the fly

packages/cms/src/components/ProfileRenderer.jsx, packages/cms/src/utils/hashCode.js
Closes #980
Sorry for the incorrect branch name.
The goal of this PR is to add a unique token to the POST operation, such that if we need to turn on cloudflare caching, it can use a unique URL for storing the payload. Right now the POST endpoint has the URL form `/api/profile/{profile_id}`, with the variables object being the body of the POST. The problem here is that the url is not unique - it doesn't even include which page the user was looking at (e.g. Germany).
So, how can we make this URL unique, and reflect a "page state" suitable for caching?
What page is the user currently viewing? For this we need slugs and ids. 
When the user loads the page, they get the non-logged in version from the server. Once the client processes the login, we must fold in the user object and POST the …
=> [cms] adds variable hashing as a token generator

packages/cms/api/proxy.js, packages/cms/src/actions/profiles.js, packages/cms/src/api/mortarRoute.js, packages/cms/src/components/cards/SelectorCard.jsx, packages/cms/src/components/cards/VariableCard.jsx, packages/cms/src/components/cards/VisualizationCard.jsx, packages/cms/src/components/interface/Toolbox.jsx, packages/cms/src/profile/ProfileBuilder.jsx, packages/cms/src/reducers/status.js
Made a few changes to try to speed things up in the CMS.
- On initial load, changed from piecemeal generator gets to a full server-side promise.all fetch. Loses granularity of "26 of 53" type progress bar, but is much faster.
- Only updates redux variables once - when all have loaded.
- Adopts a "fail fast" strategy; adds a configurable generator timeout, `CANON_CMS_GENERATOR_TIMEOUT`, which defaults to 5000ms. This may need to be set higher for OEC, but it's important that this is configurable
- Dynamically hides toolbox elements underneath modals. This means modals take slightly longer to open and close, but once they are open, typing inside them is much nicer.
I've learned that updating redux is... chunkier than I'd like. I plan to continue to investigate ways to speed up the cms, …
=> [cms] Performance improvements

packages/cms/src/actions/profiles.js, packages/cms/src/api/cmsRoute.js, packages/cms/src/components/cards/SelectorCard.jsx, packages/cms/src/components/cards/TextCard.jsx, packages/cms/src/components/cards/VariableCard.jsx, packages/cms/src/components/cards/VisualizationCard.jsx, packages/cms/src/components/interface/Dialog.css, packages/cms/src/components/interface/Toolbox.jsx, packages/cms/src/reducers/formatters.js, packages/cms/src/reducers/resources.js, packages/cms/src/reducers/status.js
Closes #901
Closes #793 
This PR refactors the Redux create and update path for all entities. This has two major benefits:
- On write errors, don't close window. Allows user to save/rescue their work (#901)
- Unifies auto-open logic so that all entities, not just Toolbox entities, open after creation (#793)
=> Issue 901 error catches

packages/cms/src/api/mortarRoute.js, packages/cms/src/components/cards/VariableCard.jsx
Removes needless `/api/variables` and `/api/internalprofile` subrequests, simplifying cache clearing and reducing request count.
Also fixes small bug with calculating variable duplicates.
=> Remove subrequests

packages/cms/README.md, packages/cms/scripts/migration/canon-cms-migrate-0.1.js, packages/cms/scripts/migration/canon-cms-migrate-0.11.js, packages/cms/scripts/migration/canon-cms-migrate-0.12.js, packages/cms/scripts/migration/canon-cms-migrate-0.6.js, packages/cms/scripts/migration/canon-cms-migrate-0.7.js, packages/cms/scripts/migration/canon-cms-migrate-0.8.js, packages/cms/scripts/migration/canon-cms-migrate-0.9.js, packages/cms/scripts/migration/canon-cms-migrate-legacy.js, packages/cms/scripts/migration/migrationUtils.js
Closes #916
Putting db creds in `CANON_CONST_*` automatically promotes them to the redux store, which comes over the wire on pageload. Renames them to `CANON_CMS_*` to avoid this, while maintaining backwards compatibility. Updates readme.
=> fixes security hole in canon vars

packages/cms/README.md, packages/cms/api/testRoute.js, packages/cms/src/actions/profiles.js, packages/cms/src/api/mortarRoute.js
Allows users to create a customAttributes endpoint at `/api/cms/customAttributes/:pid` to inject customized variables into the Attributes generator.
This allows arbitrary axios/js to be run AFTER the magic generator has retrieved the id/dimension/hierarchy but BEFORE the rest of the generators and materializers run. The user can then inject whatever variables they want, for use in subsequent `variables` operations or using `<brackets>` in API calls.
Though this makes an "internal call" to an api route, because it is a `POST`, no special considerations are needed when it comes to caching.
More information is available in the README.
=> [cms] Custom Attributes endpoint

packages/cms/src/components/sections/Hero.jsx
Currently, in DataMexico I was trying to implement a mockup done by Gaby, but I couldn't because heading didn't have a wrapper. 
This PR creates a div container for wrapping heading.
=> [cms] includes a div container for wrapping heading

packages/cms/src/api/imageRoute.js, packages/cms/src/api/mortarRoute.js, packages/cms/src/api/searchRoute.js, packages/cms/src/utils/populateSearch.js
In the canon example app, failing to set `CANON_CMS_CUBES` env var caused the load to fail. Add fallbacks so users can build with no env vars at all.
=> [cms] Adds fallback value for `CANON_CMS_CUBES`

packages/logiclayer/src/api/logiclayer.js, packages/logiclayer/src/cache/cube.js
canon apps that use logic layer can now successfully build (and show an error) if `CANON_LOGICLAYER_CUBE` is not set.
=> prevents Logic Layer from crashing build without config var

packages/cms/README.md, packages/cms/src/api/searchRoute.js
- Use `unaccent` package from postgres. 
- Refactor in searchRoutes for `/api/profilesearch` endpoint.
- There is a test record with special chars in test database: `Horsés` and keywords `úúuu`,`èèè`,`test`,`lomas de zamorá`
- To test the name comparison try http://localhost:3300/api/profilesearch?query=horse or http://localhost:3300/api/profilesearch?query=horsé 
- Also I fixed the keywords comparison. To test it try: http://localhost:3300/api/profilesearch?query=úuu or http://localhost:3300/api/profilesearch?query=zamora
- Fallback to old code if `unaccent` package is not available.
- Warning message in log on first run if package is not available.
- The only instruction to update the database server is `CREATE EXTENSION IF NOT EXISTS unaccent;`
=> [cms] improve search legacy API to support special chars fixed #1061

packages/cms/src/components/sections/Hero.jsx
On DataMX, For really-long product names, I setted the max number of lines along with a text overflow, but I would like to keep the ability to show the full name if any user is interested. This PR includes `title` tag on `cp-hero-heading-dimension`.
=> [cms] Includes title attribute into cp-hero-heading-dimension span

examples/api/cmsTestRoute.js, packages/cms/src/actions/profiles.js, packages/cms/src/api/mortarRoute.js, packages/cms/src/components/cards/VariableCard.css, packages/cms/src/components/cards/VariableCard.jsx
Adds request duration to CMS generators:
Picture is slightly inaccurate, current windows are:
- ok: 0-500ms
- warning: 500-5000ms
- danger: 5000ms+ 
Makes use of axios interceptors for timing. Someday I should allow for sorting based on problem factors (big payloads, long durations). That work will be tracked in issue #1084.
Closes #1083
=> [cms] adds request duration to cms generators

packages/cms/README.md, packages/cms/src/api/searchRoute.js
Adds the ability to specify `dimension`, `hierarchy`, and `profile` as params in profileSearch. `profile` accepts either an integer `id`, or for unary profiles, the profile `slug` for convenience.
Also handles an issue where levels were not being enforced in search results.
Closes #1089 
Closes #1092
=> [cms] adds filtering to profilesearch

packages/cms/src/api/mortarRoute.js, packages/cms/src/api/searchRoute.js, packages/cms/src/utils/prepareProfile.js
This commit fixes a messed up merge here:
https://github.com/Datawheel/canon/commit/56a2d0e22da47acb9a577e8dde452f04251be6f2
Two major situations:
In the "no roundtrips" branch, `prepareProfile.js` was written to unify server and client side profile generation. Separately on master, some adjustments and bugfixes were made to mortarRoute directly, such as handling empty multiselects for CDC. This resulted in the doubling of the profile prep code, which has now been deduped.
A refactor on one branch made `rowToResult` a global function, but a refactor on another branch added `attr` to the payload for a feature request. This commit fixes the merge by adding the `attr` return to the now unified, global function.
I hope I got everything here.🤞
=> [cms] fixes botched merge in mortar and search routes

packages/cms/src/components/editors/VariableEditor.jsx, packages/cms/src/components/interface/VisibleSelector.css, packages/cms/src/components/interface/VisibleSelector.jsx, packages/cms/src/profile/SectionEditor.jsx
Fixing this while passing through.
TextCards have advanced overrides for `allowed`, for custom string-based alloweds. There is no way here to catch for user error, as the user may have chosen to write `variableThatWontExistUntilSome[[Selector]]Happens` as their variable.
However, Generators and Sections do not currently support custom alloweds. They could, but in the interest of simplifying the interface, these top-level entities shouldn't need custom alloweds (famous last words?).
(Current allowed for sections - no custom)
This PR simply adds a text warning if the variable has been deleted out from underneath the allowed. Though this situation is possible/correct for advanced setups, I am simply trying to help new users avoid pitfalls with messages like this.
=> [cms] adds warning to broken dropdowns

packages/core/src/components/LazyImage.jsx
@palamago seems to have just been an issue using `<>` instead of the more explicit `<Fragment>`?
Test it for me to double-check... but ¯\\\_(ツ)\_/¯
=> fixes missing key error in LazyImage

packages/cms/src/components/Viz/Options.jsx
The `dataAttachments` feature of visualizations, introduced in #1068, used `response.request.responseURL` to determine the filename of each attachment. The `responseURL` of the XMLHttpRequest spec is currently not supported in IE, resulting in an `undefined` error.
This PR switches the use of `responseURL` for `response.config.url`, which is more widely supported. I tested this in Chrome and IE 11, and can also confirm this fixes the problem in the CDC-PHA environment.
=> fixes IE dataAttachments

packages/cms/src/api/mortarRoute.js
1. Adds cube restriction to `&slugs` lookup to prevent incorrect slugs on duplicate ids
2. Allows for `<magicvars>` to be varswapped in the `&slugs` lookup.
Closes #1130
=> Issue 1130 disambiguate slugs

examples/app/routes.jsx, packages/cms/src/api/mortarRoute.js, packages/cms/src/components/Profile.jsx, packages/cms/src/utils/linkify.js, packages/core/README.md, packages/core/src/server.jsx
Adds dynamic redirects to canon-core, and implements them automatically in the cms. This will require a minor release of both.
In Core, `needs` can now return a `canonRedirect` object, which contains values to swap in to the routes vars, such as `:slug` or `:id`. Docs are included in canon-core README.
In CMS, all profile ids now 301 permanent redirect to vanity slugs, making use of the above code. 
Closes #1095
=> Issue 1095 redirects

packages/cms/src/components/editors/VisualizationEditorUI.jsx, packages/cms/src/components/sections/components/Selector.jsx, packages/cms/src/components/sections/components/Subnav.css
- fixes bug with single length data vizzes in new simple-ui (7a07e89)
- fixes "manual-none" appearing in tooltip tbody in new simple-ui (7a07e89)
- adds string length cutoff to Selector radio/select switch, when any option is over 40 characters long, it switches the whole thing to a `<select>` (8d840db)
- fixes incorrect Subnav top placement on scroll (b7a4e82)
=> [cms] small bugfixes

packages/vizbuilder/src/store/cubes/selectors.js, packages/vizbuilder/src/store/query/selectors.js
The issue was caused because the list of measures by tableName was being grouped directly using the property value, and all measures without it were being grouped on a `undefined` table.
Closes #1148
=> [vizbuilder] fixes big list of datasets on undefined table

packages/cms/src/components/Viz/Viz.jsx
This 1 line is what was interfering with DataPerú's custom Sankey implementation, which returns nodes and links from the dataFormat function. That complex return object (containing a d3plus "data" key and nodes/links keys) was getting incorrectly flagged here as a Tesseract formatted data object (containing "data" and "source" keys).
The d3plus internal data loading logic has sort of leapfrogged this CMS catch in terms of intelligence detecting URLs, so by simply removing this we just lean on the d3plus internals (tested with the giant DataPeru geo profile).
=> fixes d3plus nested dataFormat usage

packages/cms/src/utils/d3plusPropify.js
These overrides have now actually been integrated into the core of d3plus, so they can be removed from here. In fact, these overrides may have actually been overriding a CMS user's config if they were trying to explicitly _show_ certain x axis labels and styles.
=> removes unnecessary d3plus axis overrides

packages/core/src/client.jsx
Updates the canon-core client.jsx code to use the nav-height and subnav-height CSS vars defined in style.yml to offset anchor link clicks.
=> uses nav-height and subnav-height to offset anchor link clicks

packages/cms/src/components/Viz/Options.jsx
A bug was found in PHLIP (and reproducable in the canon example app) where:
- keyboard tab navigation to highlight a Tab in Option.jsx
- press return to open the Dialog
- press esc to close the Dialog
- any subsequent return press causes the Dialog to quickly open/close
I'm really not sure why this blur function was added, but removing it solves this issue. 😅
=> fixes keyboard navigation for subsequent Options panel open/close

examples/app/routes.jsx, examples/package.json, packages/cms/package.json, packages/core/package.json, packages/core/src/server.jsx, packages/logiclayer/package.json, packages/vizbuilder/package.json, pnpm-lock.yaml
This PR enables setting a `status` property in a `<Route />` tag, to use that status code as the HTTP status code returned by the server when that route matches.
Should be used by default to set a 404 status code in match-all `NotFound` components.
Closes #1167
=> Adds per-route HTTP status code support

examples/api/cmsTestRoute.js, examples/api/customAttributes.js, examples/api/proxy.js, examples/app/style.yml, packages/cms/src/components/ProfileRenderer.jsx, packages/cms/src/components/interface/Outline.css, packages/cms/src/components/sections/Section.jsx, packages/cms/src/components/sections/SubGrouping.jsx, packages/cms/src/components/sections/components/Subnav.css, packages/cms/src/components/sections/components/Subnav.jsx, packages/cms/src/utils/sectionIconLookup.js, packages/core/src/components/AnchorLink.jsx
Front-facing changes:
* adds a catch for missing section slugs in ProfileRenderer (`section-<id>`), which fixes SubNav breaking because of 1 missing slug and also fixes React key errors caused be `undefined` keys
* truncates long section titles with an ellipsis in the CMS ribbon design (Outline.css)
* adds new SubGrouping section type which extends Grouping
* fixes Subnav dropdown menu placement when `subnav-height` is different than `nav-height`
* updates headingLevel logic to include current SubGrouping hierarchy in ProfileRenderer (ie. `h2`/`h3`/`h4`)
* adds new 2nd row to SubNav when SubGroupings are present
* centers SubNav links (rather than stretching them to fit full width)
* detects top of section `<div>`, rather than top of `<a>`, when determining the "active" section for SubNav …
=> adds SubGrouping section type and SubNav behavior

README.md, packages/cms/README.md, packages/core/README.md
Made some small edits to update/enhance the Canon docs.
Included changes:
- added summaries to root level README for packages (for the noobs like myself)
- made some edits to the purpose statement of the Canon CMS (@jhmullen let me know if you hate it and I can revert it)
- added small section for detailing how to bypass CORS issues with simple proxy when connecting a Canon app to a local Tesseract instance
- updated described Canon boilerplate to match current create-canon output
=> Updated Local Installation Steps in READMEs

examples/app/App.css, examples/app/pages/cms/Search.jsx, packages/cms/README.md, packages/cms/src/api/cmsRoute.js, packages/cms/src/api/searchRoute.js, packages/cms/src/components/fields/ProfileColumns.css, packages/cms/src/components/fields/ProfileColumns.jsx, packages/cms/src/components/fields/ProfileSearch.css, packages/cms/src/components/fields/ProfileSearch.jsx, packages/cms/src/components/interface/Navbar.jsx, packages/cms/src/components/sections/components/Subnav.css
This PR mainly focuses on introducing faceted search to the `<ProfileSearch />` component, but also includes a few other small tweaks and fixes that crept in as I worked. Since there's been quite a few changes, it might be worth looking at specific commits to help review my changes. I've grouped the changes into the following areas:
* adds an `api/cms/profiles` endpoint which returns `meta` _and_ `content` for all profiles (5f8fce2)
* adds cubeName filter to profileSearch (974dc97)
* adds comma-separated support for the `profile` filter in profileSearch (974dc97)
* adds `filters` to ProfileSearch, including 4 methods for labeling/organizing the search hierarchies (b16b2f7 and b484c1c)
* adds a new "grid" display option (b16b2f7)
* adds renderListItem and renderTile props (03ef530)
* hides …
=> ProfileSearch faceted search and other enhancements

packages/core/src/client.jsx, packages/core/src/helpers/maybeRedirect.js, packages/core/src/server.jsx
301 redirects were only implemented server side, so local hrefs weren't properly forwarding. 
This PR abstracts the redirect logic to an external helper file, and implements it in client.jsx.
@davelandry I'm using `router.push` client side if I determine that a redirect is necessary. This works in my testing, can you let me know if I should be doing something different here?
=> adds redirects to clientside

packages/cms/src/components/Viz/Table.jsx
A faulty if/then prevented straight data from loading in table.jsx
=> hotfixes table loading by removing bad control flow

packages/cms/src/components/Viz/Table.jsx
As @davelandry pointed out, I caused a race condition regression by removing the url-checker from Table.jsx. This should address that.
=> addresses race condition regression

packages/cms/src/components/fields/ProfileSearch.jsx
When testing the new filterQueryArgs feature in CIREN, I encountered a race condition where the default examples would fire before the setState of the componentDidMount router inspection, and they would replace the query args with the current empty state from constructor.
=> fixes race condition in ProfileSearch with queryArgs and showExamples

packages/cms/README.md, packages/cms/src/components/Viz/Table.jsx
Fixes passthrough for `Header` in react-table, also adds a `cellStyle` callback to allow partial access to the `Cell` function
=> Fix table passthru

packages/cms/README.md, packages/cms/src/components/fields/ProfileSearch.jsx, packages/cms/src/components/sections/Hero.css, packages/cms/src/components/sections/Hero.jsx, packages/core/src/i18n/canon.js
* adds ProfileSearch "All" text to default canon i18n translations (closes #1199)
* adds default props to ProfileSearch and fixes encoding error in query display
* uses ProfileSearch filters in Hero search (closes #1186)
=> [cms/core] ProfileSearch improvements

examples/package-lock.json, packages/cms/src/api/statusRoute.js, packages/core/src/api/statusRoute.js, packages/test/package.json, packages/test/src/app.js, packages/test/src/index.js, packages/test/src/public/normalize.css, packages/test/src/public/styles.css, packages/test/src/templates/partials/layout.liquid, packages/test/src/templates/partials/result-block.liquid, packages/test/src/templates/partials/result-item.liquid, packages/test/src/templates/partials/status.liquid, packages/test/src/templates/views/results.liquid, packages/test/src/tests/AppsChecker.js, packages/test/src/tests/CommandsChecker.js, packages/test/src/tests/ServicesChecker.js, pnpm-lock.yaml
- Return expected and installed version of itself
- Return expected and installed version of itself
- One single route now that supports format param: `html` or `json` defaults `html`.
- html version created with `liquidjs` simple html templates.
Warning: I added a `package-lock.json` file as an example to test the new api routes. I understand that is not affecting the current flow of `pnpm`
Thanks!
=> Status api

packages/cms/src/db/profile_meta.js
Added relation between `search` and `profile_meta` tables.
Related with: https://github.com/Datawheel/oec-site/pull/356
=> New associate in profile_meta model

packages/cms/src/components/fields/ProfileSearch.jsx, packages/cms/src/components/sections/Hero.jsx, packages/cms/src/utils/formatters/stripHTML.js
* adds basic HTML entity stripping to stripHTML formatter - fixes `&nbsp;` appearing in OEC Hero search input (5463989)
* fixes bug in Hero spanifyTitle with titles within other titles - fixes "Brazil Nuts in Brazil" (4a7fd8b)
* enables showExamples in the default Hero ProfileSearch - thought this was nice behavior (708faa6)
* resets ProfileSearch filters when clicking the "X" button - requested by OEC (a4d910b)
=> [cms] hero search bugfixes

packages/core/README.md, packages/core/bin/server/steps/store.js, packages/core/src/CanonProvider.css, packages/core/src/CanonProvider.jsx, packages/core/src/helpers/services.js, packages/core/src/i18n/canon.js, packages/core/src/server.jsx, packages/core/src/storeConfig.js, packages/vizbuilder/src/types/state.d.ts
This PR closes #685 by adding 2 new environment variables:
* `CANON_GDPR` - setting this to `true` will show a minimally styled fixed position box on the bottom of the screen (shown here in screenshot) that will ask the user to accept/deny the use of tracking code (all text is stored in the locale files for translation/modification). Tracking code is only run when the user clicks "Accept", or they refresh the page (the lack of response is considered "consent").
* `CANON_GDPR_WAIT` - setting this to `true` requires a user to click "Accept" in order to run the tracking code, resulting in the pop-up being shown on every page visit until they either accept or reject.
=> GDPR support

packages/core/webpack/config/postcss.js
We currently use the `postcss-css-variables` plugin to enable the use of [custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) in our CSS. At one time, this feature was a future spec of CSS, but is actually now supported in all modern browsers.
In it's current implementation, this plugin will take the following source code:
```css
:root {
--color: green;
}
button {
background: var(--color);
}
```
And turn it into this, so that it can be read by all browsers:
```css
button {
background: green;
}
```
My proposed one-line change, adding `preserve: true` to the config of the plugin, makes the output look like this:
```css
:root {
--color: green;
}
button {
background: green;
background: var(--color);
}
```
This allows IE to still render the correct …
=> [core] preserves custom properties in transpiled CSS

packages/cms/src/components/interface/LoginForm.jsx, packages/core/src/auth/local.js, packages/core/src/components/Login.jsx
This fixes an issue, visible in the OEC, where regardless of what a user types into the Login form for credentials, it will always show the "Successful login" toast (but they won't be logged in, so no security problem, just confusion). 
Logins still work if the credentials are correct, there was just a race condition between the initial `isAuthenticated` fetch and the first "Submit" click in the form. I'm not comparing the `auth` prop against the previous prop, and only running the Toast logic if they are entirely different objects (meaning an actual redux state change has occurred for that key).
=> [core] login toast fix

examples/app/components/mixins.css, examples/app/style.yml, packages/cms/app/style.yml, packages/cms/src/components/Showcase.css, packages/cms/src/components/Viz/Table.css, packages/cms/src/components/cards/Card.css, packages/cms/src/components/editors/AceTheme.css, packages/cms/src/components/editors/RichTextEditor.css, packages/cms/src/components/fields/FilterSearch.css, packages/cms/src/components/fields/PreviewSearch.css, packages/cms/src/components/fields/ProfileTile.css, packages/cms/src/components/fields/Select.css, packages/cms/src/components/interface/Alert.css, packages/cms/src/components/interface/AuthForm.css, packages/cms/src/components/interface/Deck.css, packages/cms/src/components/interface/Dialog.css, packages/cms/src/components/interface/Dropdown.css, packages/cms/src/components/interface/Navbar.css, packages/cms/src/components/interface/Status.css, packages/cms/src/components/sections/components/Subnav.css, packages/cms/src/components/variables/ConsoleVariable.css, packages/cms/src/css/base.css, packages/cms/src/css/mixins.css, packages/cms/src/member/MetaEditor.css, packages/core/package.json, packages/core/src/components/Forms.css, packages/core/src/variables.css, packages/core/webpack/config/postcss.js, packages/create-canon/scaffold/app/style.yml, pnpm-lock.yaml
@jhmullen here's the big `color( )` removal. I've written the upgrade steps here that can be copy/pasted over to release notes, and I think the following release strategy might work best:
1. release this as canon-core v0.24.0
2. go back to the commit tag for v0.23.0, and cut a v0.23.3 release that reverts the changes introduced in v0.23.1 and v0.23.2 (as they will break any existing `color( )` behavior)
Add the following block to `style.yml`:
```yml
white-RGB: 255, 255, 255
light-1-RGB: 248, 249, 250
light-2-RGB: 236, 239, 241
light-3-RGB: 207, 218, 226
gray-RGB: 174, 189, 204
dark-1-RGB: 138, 151, 174
dark-2-RGB: 42, 47, 59
dark-3-RGB: 32, 36, 46
black-RGB: 24, 26, 33
accent-light-RGB: 255, 214, 91
```
Convert all instances of `color( )` in CSS to use a different method, typically `rgba( …
=> [core] removes postcss-color-function and all color references in CSS

examples/app/pages/cms/Search.jsx, packages/cms/README.md, packages/cms/src/components/fields/ProfileSearch.jsx
I added the ability of pass an array of ignored terms for `<ProfileSearch>` component.
- ProfileSearch receives now a new prop called `ignoredTerms` (empty array by default) then in the constructor a regex is built once. On every change (user input), the regex is applied to the `query` and is passed cleaned to `/profilesearch` service. I created an extra regex to remove mulitple spaces caused by remove some forbidden words or users error.
- Readme file with `<ProfileSearch>`'s props available updated.
Extra: Nice resource here to get a full list of stop words in json in different languages here: https://countwordsfree.com/stopwords
=> Ignore terms in profile search #1252

packages/cms/README.md, packages/cms/src/api/searchRoute.js, packages/cms/src/components/fields/ProfileSearch.jsx
Fixed: https://github.com/Datawheel/canon/issues/1284
UDD project is using the legacy search and they have a bilateral profile so we need to improve some results.
- New prop in `ProfileSearch` that forces to show more results from bilaterals.
- Change in `api/profilesearch` to include bilaterals combinations using the top 5 by `zvalue` 
- Readme update with the new prop
SORRY: some ESLint and Prettier formatting was applied in the files I changed.
=> Improve search for bilateral profiles #1284

packages/cms/src/components/sections/components/Subnav.jsx
This is an attempt to resolve the behavior seen in Healthy Cape Fear where the SubNav does not highlight the correct Grouping after clicking it in the SubNav: https://alpha.cfc.datawheel.us/profile/geo/cape-fear#social-and-economic-factors
When doing some browser inspection, the `top` values for Cape Fear are coming back with decimal pixel values that I believe are making this not trip.
=> [cms] rounds down calculated top position of sections in SubNav

packages/core/src/client.jsx
In Healthy Cape Fear, we noticed that clicking the link for a Grouping section from the SubNav would result in the previous Grouping being highlighted in the SubNav. That is because this 10 pixel padding was put in at some point (probably by me) to make scrolling look "prettier" by forcing a little top padding when scrolling to a section. 
The SubNav doesn't take this invisible padding override into account when detecting if a section has hit the "top" of the screen, nor should it IMO. I propose we just remove it from the global behavior in `core`.
=> [core] removes unnecessary (and often conflicting) 10 pixel padding from scroll behavior

packages/core/webpack/config/common.js, packages/core/webpack/config/postcss.js, packages/core/webpack/dev-client.js, packages/core/webpack/dev-server.js, packages/core/webpack/prod.js
The [resolve parameter](https://github.com/postcss/postcss-import/tree/12.0.1#resolve) in `postcss-import` allows a custom resolve procedure, using node's native resolve function. This commit adds the possibility to resolve the `$app` and `$root` aliases, set in webpack.
Still, a more streamlined way, using the same configuration object, would be preferred.
Closes #1283
=> adds custom resolve function to postcss

.gitignore, examples/canon.js, packages/cms/README.md, packages/cms/src/api/sitemap.js, packages/cms/src/utils/sequelize/profiles.js
New sitemap generation for `canon-cms`:
Features:
- SitemapIndex generated that collects all the generated sitemaps in one single url.
- User defined urls sitemap. 
- Stories sitemap (includes rss).
- Profiles sitemap (one sitemap per profile type).
Take a look into the [readme file](https://github.com/Datawheel/canon/tree/sitemap-generation/packages/cms#sitemaps) to see a full description of the implementation.
=> Sitemap generation

packages/core/src/CanonProvider.jsx, packages/core/src/helpers/services.js, packages/core/src/server.jsx
- Google optimize is loaded like the rest of the services.
- Respect GDPR
- JS code create a `<script>` tag at the very top of `<head>` (required)
- Fix bug in general click button handle that happens just with "accept gdpr" because ga exists but is not fully loaded yet.
=> Change google optimize load strategy to respect GDPR

packages/core/bin/server/steps/store.js, packages/core/src/CanonProvider.jsx, packages/core/src/client.jsx, packages/core/src/helpers/services.js, packages/core/src/server.jsx
- Rolled back to load the script at the very beginning of `<head>`.
- We found an "infinite loop" issue implementing the redirect test strategy into oec, so we moved to a "custom event" launch strategy to give us more control and a better performance.
See more under "Option 2..." title here: https://support.google.com/optimize/answer/7008840?hl=en
=> Optimize support, again

packages/cms/README.md
The docs listed `-t` as the argument to set the number of threads, but this was changed at some point to `-w`.
=> updates canon-cms-warmup docs

packages/cms/src/components/Viz/Viz.jsx
These "hidden" options are needed for the Cape Fear project, and are actually also used in the custom Data USA CMS, which allows certain visualizations (like top/bottom rankins charts) to display the entire dataset in the View Data panel.
=> adds viewData and viewDataFormat config options

packages/cms/README.md, packages/cms/src/components/Profile.jsx, packages/cms/src/components/ProfileRenderer.jsx, packages/cms/src/components/fields/ProfileSearch.css, packages/cms/src/components/sections/Hero.css, packages/cms/src/components/sections/Hero.jsx, packages/cms/src/components/sections/components/Selector.jsx, packages/core/src/i18n/canon.js
This PR adds **side-by-side comparisons** for unilateral profiles, presenting the user with an "Add Comparison" button underneath the Hero title/subtitle when `CANON_CONST_PROFILE_COMPARISON` is set to `true`:
Clicking this button opens an instance of `ProfileSearch`, faceted to show only members belonging to the currently viewed profile:
Clicking on any of these results will cause the following chain of actions:
- the default `Loading` component is shown
- the secondary comparison profile contents are fetched from the same API used for the initial profile
- the comparison contents are folded in alongside each of the current profile's sections, converting each matched set of sections into a grouped pair of `Column`-type sections.
- a "Remove Comparison" button is attached, fixed, to the …
=> implements profile comparison feature based on Data USA

packages/cms/src/components/ProfileRenderer.jsx, packages/cms/src/components/sections/Hero.jsx
- only suffixes comparator name to section titles if it does not already exist in the title
- fixes nested SubNav in comparisons
- hides sections when one of the comparators does not exist
- filters out sections with only their Grouping in comparison mode
- adds className to comparison button
- moves comparison button into cp-hero-heading-wrapper
- hides current profile from comparison search
=> profile comparison hotfixes

packages/cms/src/components/fields/ProfileSearch.jsx
This PR adds the current profile title ("Country", "Subnational", etc) as the 2nd argument in each filter title function (`filterCubeTitle`, `filterCubeTitle`, and `filterCubeTitle`). This is needed for the OEC in order to differentiate between the subnational profiles for Germany and the new product profiles based on the German EGW classification (they're both the same underlying cube).
=> adds current profile title as 2nd argument for ProfileSearch filter title functions

packages/cms/src/api/searchRoute.js
Remove Lunr reserved chars from query.
Related with :
- https://github.com/Datawheel/canon/issues/1368
- https://github.com/Datawheel/sebrae-site/issues/136
The search below becomes `+cars~1* +large~1* +sized~1*`. A valid lunr search term.
=> Sanitize LUNR search terms

examples/api/socketRoute.js, examples/app/pages/Docs.jsx, examples/app/pages/core/Socket.jsx, packages/core/bin/server/steps/router.js, packages/core/package.json, pnpm-lock.yaml
The core change here is in `packages/core/bin/server/steps/router.js`, where I have added a Socket.IO wrapper to extend the internal Express router to accept Socket connections. This allows for API endpoints to send progress to the browser, allowing for indicators such as this new example:
https://user-images.githubusercontent.com/1847581/207712880-d7ba394d-304b-45fc-8d51-b2a2e2650682.mov
=> [core] adds express handlers and examples for socketio integrations

packages/cms/src/api/imageRoute.js
Should remove necessity of setting `CANON_CONST_STORAGE_BUCKET` in every deployment that uses images
=> fixes need for bucket in image route

package-lock.json, packages/next/cms/components/Viz/Graphic.js, packages/next/cms/components/Viz/Viz.js, packages/next/cms/components/fields/ComparisonButton.js, packages/next/cms/components/fields/ProfileSearch.js, packages/next/cms/components/fields/ProfileTile.js, packages/next/cms/components/sections/Hero.js, packages/next/cms/components/sections/MultiColumn.js, packages/next/cms/components/sections/components/SectionGrouping.js, packages/next/cms/components/sections/components/Selector.js, packages/next/cms/components/sections/components/Stat.js, packages/next/cms/hooks/use-comparison.js, packages/next/cms/hooks/use-on-set-variables.js, packages/next/cms/hooks/use-profile-sections.js, packages/next/cms/hooks/use-report-state.js, packages/next/package.json, packages/next/utils.js
I had to do a couple of patch releases with some fixes I needed for monshaat. All very small changes, with bugfixes and added classes for styling. Broad explanation ahead:
`0.2.1`:
- fixes a bug that prevented importing the package
`0.2.2`: 
- adds a className for targeting comparison button state
- if there is an error on the comparison query, delete the query param
- fixes "remove comparison" icon
- fixes bad import on `next/router` -> `next/router.js` (ESM complains)
- adds className to image credits
- fixes ProfileTile's `titleSize` fn for arabic charset.
- adds className for profilesearch filters
- delete unused params on profilesearch (To be added back? throws an error now)
- fixes comparison section types (og profile were Default, but comparison profile TextViz)
`0.2.3` - `0.2.4`: …
=> Fixes/canon next@0.2.x

packages/next/cms/components/fields/ProfileSearch.js
After testing with the latest release I found a weird focus behavior. The usefocus hook conflicted with the FocusTrap mantine component. So I opted in to use the current mantine implementation and found a simpler and elegant solution, that solves the input focus issue.
=> simplify & focus with current FocusTrap mantine component
