Datawheel/canon

webpack/webpack.config.dev-server.js

I didn't test this. Please do before merging :)

fixes #70 and #71

---

app/routes.jsx
package-lock.json
src/server.jsx

adds support for setting the language as the first element in a URL

---

db/testTable.js
src/auth/social.js
src/db/users.js

This PR fixes the edge case bug of #93 by adding a new field to the user model to store emails from social user logins in a separate field in the database.

Bug fix for duplicated email with social users

---

README.md
package-lock.json
src/server.jsx

Adds Facebook Pixel tracking to the head tag via server.jsx.  This adds a new environment variable, `CANON_FACEBOOK_PIXEL`.  The readme has been updated.

Add Facebook Pixel to Server

---

packages/vizbuilder/src/helpers/chartconfig.js

[vizbuilder] Removes chart type from chart titles

---

packages/vizbuilder/src/index.js

reorders default visualizations

---

packages/vizbuilder/src/actions/fetch.js
packages/vizbuilder/src/components/Sidebar/ConditionManager/ConditionPropertySelect.jsx
packages/vizbuilder/src/components/Sidebar/LevelSelect.jsx
packages/vizbuilder/src/components/Sidebar/index.jsx
packages/vizbuilder/src/helpers/formatting.js
packages/vizbuilder/src/helpers/sorting.js

[vizbuilder] Hierarchy incompatibilities and duplicated levels in selector

---

packages/vizbuilder/src/components/Sidebar/MultiLevelSelect/index.jsx

[vizbuilder] input spaces in filter for MultiLevelSelector

---

packages/vizbuilder/src/helpers/chartconfig.js

[vizbuilder] allows "UNKNOWN" aggregation type

---

packages/vizbuilder/src/actions/fetch.js
packages/vizbuilder/src/index.js

[vizbuilder] add default props to main component

---

packages/vizbuilder/src/components/BaseSelect.jsx

yes, it was this simple. shame on me. 😢 
closes #128

fixes first item always selected in BaseSelect

---

packages/vizbuilder/src/components/Sidebar/MeasureSelect.jsx
packages/vizbuilder/src/helpers/formatting.js
packages/vizbuilder/src/helpers/sorting.js

shows all measures in selector

---

packages/vizbuilder/src/components/Sidebar/ConditionManager/ConditionItem.jsx
packages/vizbuilder/src/components/Sidebar/ConditionManager/ConditionItemFilter.jsx

enables float values on measure filters

---

packages/vizbuilder/src/components/Sidebar/ConditionManager/index.jsx

adds title to filter section

---

packages/vizbuilder/app/pages/Home.jsx
packages/vizbuilder/src/actions/fetch.js
packages/vizbuilder/src/components/Sidebar/index.jsx
packages/vizbuilder/src/helpers/sorting.js
packages/vizbuilder/src/index.js

implements multiple default dimensions/drilldowns

---

packages/vizbuilder/scripts/cubes-audit.js
packages/vizbuilder/scripts/cubes-audit.md
packages/vizbuilder/src/helpers/chartconfig.js

(closes #154 #159)
Adds a `canon-audit` script to vizbuilder for to check uncompleted annotations in cubes.
1. Execute `node scripts/cubes-audit.js`
2. In `scripts/cubes-audit.md` you can see a markdown file updated with the audit!
3. Enjoy updating the annotations in schemas :)

canon-audit script to review cube annotations and horizontal barcharts

---

packages/vizbuilder/src/helpers/chartconfig.js

hides treemap and barchart  when there's only 1 member available

---

packages/vizbuilder/app/pages/Home.jsx
packages/vizbuilder/src/components/ChartArea/index.jsx
packages/vizbuilder/src/helpers/chartconfig.js
packages/vizbuilder/src/index.js

Due to the amount of changes made to the features/vb-state-history branch, it's better to merge this directly to that branch instead of master.
Closes #165

[vizbuilder] Adds measureConfig attribute

---

packages/vizbuilder/src/components/ChartArea/index.jsx
packages/vizbuilder/src/helpers/chartconfig.js

hides zoom controls in small mode

---

packages/vizbuilder/src/components/ChartArea/ChartCard.jsx

adds "Log" in y-axis title

---

packages/vizbuilder/src/actions/fetch.js
packages/vizbuilder/src/components/Sidebar/index.jsx
packages/vizbuilder/src/helpers/chartconfig.js
packages/vizbuilder/src/helpers/query.js
packages/vizbuilder/src/helpers/sorting.js
packages/vizbuilder/src/state.js

[vizbuilder] adds new error_type annotation

---

packages/vizbuilder/src/components/Sidebar/ConditionManager/index.jsx

[vizbuilder] hides unnecessary measures in Filter

---

packages/vizbuilder/src/actions/fetch.js

solves #136 residual behavior

---

packages/vizbuilder/src/actions/fetch.js
packages/vizbuilder/src/components/Sidebar/MeasureSelect.jsx
packages/vizbuilder/src/helpers/sorting.js

[vizbuilder] extends measure filtering by dataset and source

---

packages/vizbuilder/src/helpers/chartconfig.js

[vizbuilder] removes total from "by year" charts

---

packages/vizbuilder/src/components/Sidebar/index.jsx
packages/vizbuilder/src/helpers/sorting.js

[vizbuilder] removes RCA measures from filter & measure selectors

---

packages/vizbuilder/src/components/ChartArea/style.css

[vizbuilder] improves width of charts in wide screens

---

packages/vizbuilder/app/pages/Home.jsx
packages/vizbuilder/package.json
packages/vizbuilder/src/helpers/query.js
packages/vizbuilder/src/helpers/sorting.js
packages/vizbuilder/src/index.js

[vizbuilder] sidebar issues

---

packages/vizbuilder/src/helpers/fetch.js
packages/vizbuilder/src/index.js

closes #223 
I'm not really sure if this is how I should handle the environment variable though. Won't the client have issues with `process.env` or is it handled by webpack?

[vizbuilder] increases TooMuchData default cap

---

packages/vizbuilder/src/components/ChartArea/index.jsx

[vizbuilder] adds new default formatters

---

packages/vizbuilder/src/helpers/chartconfig.js

[vizbuilder] adds support for pre_aggregation_method measure annotation

---

packages/vizbuilder/src/components/Sidebar/FilterManager/Filter.js
packages/vizbuilder/src/components/Sidebar/FilterManager/FilterItem.jsx
packages/vizbuilder/src/components/Sidebar/FilterManager/index.jsx
packages/vizbuilder/src/components/Sidebar/SidebarCRUDItem.jsx

[vizbuilder] fixes bug when handling float values in filters

---

packages/vizbuilder/src/components/Sidebar/index.jsx
packages/vizbuilder/src/helpers/fetch.js
packages/vizbuilder/src/helpers/sorting.js
packages/vizbuilder/src/helpers/validation.js

[vizbuilder] hides all dimensions/levels/measures with hide_in_ui annotation

---

packages/vizbuilder/src/components/Sidebar/MeasureSelect.jsx
packages/vizbuilder/src/helpers/chartconfig.js
packages/vizbuilder/src/helpers/fetch.js

fixes dataset/source tag when one of them is missing

---

packages/vizbuilder/src/components/Sidebar/select.css
packages/vizbuilder/src/helpers/chartconfig.js
packages/vizbuilder/src/helpers/formatting.js

[vizbuilder] shows current year on chart titles in general view

---

packages/vizbuilder/src/components/Sidebar/DatasetSelect.jsx
packages/vizbuilder/src/components/Sidebar/MeasureSelect.jsx
packages/vizbuilder/src/components/Sidebar/MultiLevelSelect/index.jsx
packages/vizbuilder/src/components/Sidebar/index.jsx
packages/vizbuilder/src/helpers/fetch.js
packages/vizbuilder/src/helpers/permalink.js
packages/vizbuilder/src/helpers/sorting.js

[vizbuilder] implements measure grouping by table_id annotation

---

packages/vizbuilder/src/components/Sidebar/MeasureSelect.jsx
packages/vizbuilder/src/components/Sidebar/select.css
packages/vizbuilder/src/components/Sidebar/style.css

[vizbuilder] changes MeasureSelect target to wrap overflowing text instead of hiding

---

packages/vizbuilder/src/components/Sidebar/CustomSelect/BaseSelect.jsx
packages/vizbuilder/src/components/Sidebar/CustomSelect/MonoSelect.jsx
packages/vizbuilder/src/components/Sidebar/CustomSelect/MultiSelect.jsx
packages/vizbuilder/src/components/Sidebar/CustomSelect/VirtualListWrapper.jsx
packages/vizbuilder/src/components/Sidebar/CustomSelect/index.js
packages/vizbuilder/src/components/Sidebar/GroupingManager/Grouping.js
packages/vizbuilder/src/components/Sidebar/GroupingManager/GroupingItem.jsx
packages/vizbuilder/src/components/Sidebar/MeasureSelect.jsx
packages/vizbuilder/src/components/Sidebar/MemberSelect.jsx
packages/vizbuilder/src/components/Sidebar/MultiLevelSelect/index.jsx
packages/vizbuilder/src/components/Sidebar/select.css
packages/vizbuilder/src/components/Sidebar/style.css

[vizbuilder] implements new Select class for multiple + virtual list + hierarchy

---

packages/vizbuilder/src/helpers/chartconfig.js
packages/vizbuilder/src/helpers/validation.js

[vizbuilder] validates additional measures for values different than zero on tooltips

---

packages/vizbuilder/src/components/ChartArea/index.jsx
packages/vizbuilder/src/components/Sidebar/DatasetSelect.jsx
packages/vizbuilder/src/components/Sidebar/Ranking.jsx
packages/vizbuilder/src/components/Sidebar/index.jsx
packages/vizbuilder/src/components/Sidebar/style.css
packages/vizbuilder/src/helpers/chartconfig.js
packages/vizbuilder/src/helpers/fetch.js
packages/vizbuilder/src/helpers/formatting.js
packages/vizbuilder/src/helpers/sorting.js
packages/vizbuilder/src/helpers/validation.js
packages/vizbuilder/src/index.js

closes #264
closes #265 
closes #266 
closes #267

[vizbuilder] implements sidebar related features

---

packages/cms/src/api/cmsRoute.js

Fixes pathing bug with topicTypes.  Closes #283

fixes pathing for topicTypes in cmsRoute, fixes #283

---

packages/cms/src/utils/libs.js
packages/cms/src/utils/stats.js

Adds generic stats functions from cdc to CMS libs

adds stats functions to libs

---

packages/vizbuilder/src/components/Sidebar/CustomSelect/MonoSelect.jsx
packages/vizbuilder/src/components/Sidebar/CustomSelect/MultiSelect.jsx
packages/vizbuilder/src/components/Sidebar/CustomSelect/VirtualListWrapper.jsx
packages/vizbuilder/src/components/Sidebar/MeasureSelect.jsx
packages/vizbuilder/src/components/Sidebar/MemberSelect.jsx
packages/vizbuilder/src/components/Sidebar/index.jsx
packages/vizbuilder/src/components/Sidebar/select.css
packages/vizbuilder/src/components/Sidebar/style.css
packages/vizbuilder/src/helpers/fetch.js
packages/vizbuilder/src/helpers/sorting.js
packages/vizbuilder/src/helpers/validation.js

closes #280 
closes #281 
closes #282 
closes #285

[vizbuilder] MeasureSelect-related issues

---

packages/cms/src/components/Viz/index.jsx
packages/cms/src/utils/d3plusPropify.js

wraps viz logic in try/catch to avoid RSOD in cms

---

packages/vizbuilder/.vscode/settings.json
packages/vizbuilder/app/pages/Home.jsx
packages/vizbuilder/package-lock.json
packages/vizbuilder/package.json
packages/vizbuilder/src/components/ChartArea/index.jsx
packages/vizbuilder/src/components/ChartArea/style.css
packages/vizbuilder/src/components/Sidebar/CustomSelect/MonoSelect.jsx
packages/vizbuilder/src/components/Sidebar/CustomSelect/VirtualListWrapper.jsx
packages/vizbuilder/src/components/Sidebar/FilterManager/FilterItem.jsx
packages/vizbuilder/src/components/Sidebar/FilterMeasureSelect.jsx
packages/vizbuilder/src/components/Sidebar/GroupingManager/GroupingItem.jsx
packages/vizbuilder/src/components/Sidebar/MeasureSelect.jsx
packages/vizbuilder/src/components/Sidebar/MemberSelect.jsx
packages/vizbuilder/src/components/Sidebar/select.css
packages/vizbuilder/src/components/Sidebar/style.css
packages/vizbuilder/src/helpers/chartconfig.js
packages/vizbuilder/src/helpers/formatting.js
packages/vizbuilder/src/helpers/validation.js
packages/vizbuilder/src/index.js

closes #291 
closes #293 
closes #294

[vizbuilder] variable height fixes and other minor issues

---

packages/logiclayer/src/utils/findYears.js

[logiclayer] recognizes year dimensions defined with time type

---

packages/cms/src/profile/TopicEditor.jsx

This PR ports a fix from data-usa that caused topics to not save their allowed state.

[CMS] fixes bug preventing setting allowed on topics

---

packages/cms/src/profile/TopicEditor.jsx

Topic editor was lacking Preview Search bar, this fixes that. Closes #299

fixes issue 299 and adds search bar to topic editor

---

package-lock.json
packages/cms/src/cms.css
packages/cms/src/components/editors/GeneratorEditor.jsx

hotfix for nested paragraph rendering bug

fixes paragraph nesting

---

packages/cms/src/profile/TopicEditor.jsx

topic preview was doubled up from bad merge.  Removed dupe.

fixes bug with preview doubling up from bad merge

---

packages/vizbuilder/src/components/Sidebar/CustomSelect/VirtualListWrapper.jsx
packages/vizbuilder/src/components/Sidebar/FilterManager/Filter.js
packages/vizbuilder/src/components/Sidebar/FilterMeasureSelect.jsx
packages/vizbuilder/src/components/Sidebar/Ranking.jsx
packages/vizbuilder/src/helpers/chartConfig.js
packages/vizbuilder/src/helpers/chartCriteria.js
packages/vizbuilder/src/helpers/chartHelpers.js
packages/vizbuilder/src/helpers/formatting.js
packages/vizbuilder/src/helpers/loadstate.js
packages/vizbuilder/src/index.js

closes #205
closes #331 
closes #332 
closes #335 
closes #336 
closes #337 
closes #338

[vizbuilder] Cesar's feedback and other bugs

---

packages/vizbuilder/package-lock.json
packages/vizbuilder/package.json
packages/vizbuilder/src/components/Sidebar/index.jsx
packages/vizbuilder/src/helpers/formatting.js
packages/vizbuilder/src/helpers/query.js

[vizbuilder] Plural titles and keeping parameters

---

packages/cms/src/components/cards/TextCard.jsx
packages/cms/src/db/profile_footnote.js
packages/cms/src/db/story_footnote.js
packages/cms/src/profile/ProfileEditor.jsx
packages/cms/src/story/StoryEditor.jsx

Footnotes need titles for CDC.  Here they are!

adds titles to footnotes

---

packages/vizbuilder/src/components/PermalinkManager.jsx
packages/vizbuilder/src/components/Sidebar/GroupingManager/index.jsx
packages/vizbuilder/src/components/Sidebar/SidebarCRUDManager.jsx
packages/vizbuilder/src/components/Sidebar/index.jsx
packages/vizbuilder/src/helpers/chartCriteria.js
packages/vizbuilder/src/helpers/chartHelpers.js
packages/vizbuilder/src/helpers/fetch.js
packages/vizbuilder/src/helpers/permalink.js
packages/vizbuilder/src/helpers/query.js
packages/vizbuilder/src/helpers/sorting.js

fixes bug on geomaps' chart criteria
fixes bug on permalink parsing and member loading
adds postUpdateHook on SidebarCRUDManager
fixes minor format issues

[vizbuilder] geomap not showing for certain combinations

---

packages/vizbuilder/app/pages/Home.jsx
packages/vizbuilder/package-lock.json
packages/vizbuilder/package.json
packages/vizbuilder/src/helpers/api.js

[vizbuilder] implements mondrian-rest-client MultiClient

---

packages/cms/src/components/cards/TextCard.jsx
packages/cms/src/story/StoryTopicEditor.jsx

Closes #362 and also closes #360

fixes storytopics not loading, closes #362

---

packages/cms/src/components/editors/SelectorEditor.jsx

Closes #308, allows for multiselects to have no defaults.

[cms] adds ability for multiselects to have no defaults

---

packages/cms/src/components/editors/SelectorEditor.jsx

Closes #366 , allows for setting of custom generator variables as defaults in multiselects

adds custom defaults for multiselects, closes #366

---

packages/cms/src/components/editors/SimpleGeneratorEditor.jsx
packages/cms/src/db/generator.js
packages/cms/src/db/topic_visualization.js

defaults to simple mode for gen/viz closes #353

---

packages/cms/src/utils/varSwap.js

Solves issue #364 by wrapping formatters in a try/catch.

wraps formatters in try/catch to prevent crashes for issue #364

---

packages/cms/src/api/cmsRoute.js

This PR addresses issue #357.
All GET operations that require ordering now use a new method, `flatSort`, as opposed to a simple sort by ordering.  This is to handle the edge-cases where `ordering` breaks, such as [0, 2, 2] as opposed to [0, 1, 2].
The new flatSort method sorts the array, then adjusts ordering to match indexing, effectively flattening the ordering. This avoids situations in the front-facing CMS that was causing sorting to break.
This PR also begins what will be an on-going process of replacing `.then` callbacks with `await`

overhauls sorting to include 'flatten' capability for when ordering breaks

---

packages/cms/src/api/cmsRoute.js

a missing `await` was causing topic loading to fail.

fixes bug with missing await

---

packages/cms/package-lock.json
packages/cms/package.json
packages/cms/src/db/story.js
packages/cms/src/story/StoryEditor.jsx

Adds datepicker and date column to stories, closes #361

adds datepicker to stories for issue #361

---

packages/cms/src/profile/ProfileBuilder.jsx

fixes dimensions in profilebuilder, closes #256

---

packages/cms/src/api/cmsRoute.js

adds prunesearch function to remove search entires after profile deletion

---

packages/cms/src/components/cards/GeneratorCard.jsx
packages/cms/src/components/cards/SelectorCard.jsx
packages/cms/src/components/cards/TextCard.jsx
packages/cms/src/components/cards/VisualizationCard.jsx
packages/cms/src/story/StoryBuilder.jsx

Adds delete alerts for all deletion actions, closes #240

---

packages/vizbuilder/README.md
packages/vizbuilder/src/index.css
packages/vizbuilder/src/index.js

[vizbuilder] updates README.md

---

packages/cms/db/story_subtitle.js
packages/cms/src/api/cmsRoute.js
packages/cms/src/api/mortarRoute.js
packages/cms/src/db/story.js
packages/cms/src/db/story_subtitle.js
packages/cms/src/story/StoryEditor.jsx

Closes #393 by adding subtitles to stories.
note for @davelandry : I've already performed the necessary db changes on both `cricket` and `dragonfly`.

adds subtitles to stories

---

packages/cms/package-lock.json
packages/cms/src/api/cmsRoute.js

Closes #368 by fixing pathing on windows for topic types.

fixes topictype dir on windows

---

packages/cms/src/components/Viz/PercentageBar.jsx

Simple comparison on update to rebuild viz on config change

adds didUpdate callback for percentagebar to re-render on config change

---

packages/cms/src/utils/varSwapRecursive.js

Note: issue 745 refers to the cdc-pha repo.

fixes bug where dates were changed to objects in stories

---

packages/cms/src/db/profile_stat.js
packages/cms/src/db/storytopic_stat.js
packages/cms/src/db/topic_stat.js

changes subtitles from varchar to text to make room for more characters

---

packages/vizbuilder/src/components/ChartArea/index.jsx
packages/vizbuilder/src/components/ChartArea/style.css
packages/vizbuilder/src/components/Sidebar/SidebarCRUDManager.jsx
packages/vizbuilder/src/helpers/chartConfig.js
packages/vizbuilder/src/index.css
packages/vizbuilder/src/index.js

[vizbuilder] Issues #415 and #416

---

packages/cms/src/api/cmsRoute.js

This addresses [this issue](https://github.com/Datawheel/cdc-pha/issues/775) in cdc.

fixes storytopic deletes

---

packages/vizbuilder/README.md
packages/vizbuilder/app/pages/Home.jsx
packages/vizbuilder/app/pages/Map.jsx
packages/vizbuilder/app/pages/Visualize.jsx
packages/vizbuilder/app/pages/params.js
packages/vizbuilder/app/routes.jsx
packages/vizbuilder/index.d.ts
packages/vizbuilder/index.js
packages/vizbuilder/package.json
packages/vizbuilder/src/components/Sidebar/FilterManager/FilterItem.jsx
packages/vizbuilder/src/components/Sidebar/GroupingManager/GroupingItem.jsx
packages/vizbuilder/src/helpers/chartConfig.js
packages/vizbuilder/src/helpers/chartCriteria.js
packages/vizbuilder/src/helpers/chartHelpers.js
packages/vizbuilder/src/helpers/formatting.js
packages/vizbuilder/src/helpers/loadstate.js
packages/vizbuilder/src/helpers/query.js
packages/vizbuilder/src/index.js
packages/vizbuilder/src/reducers/index.js
packages/vizbuilder/src/state.js

closes #433 
closes #434 
closes #435 
closes #437 
closes #438 
closes #439

[vizbuilder] new feedback

---

packages/vizbuilder/src/components/Sidebar/MemberSelect.jsx
packages/vizbuilder/src/helpers/chartCriteria.js
packages/vizbuilder/src/helpers/sorting.js
packages/vizbuilder/src/index.js

closes #451 
closes #452 
closes #454 
closes #456

[vizbuilder] bug feedback

---

packages/vizbuilder/README.md
packages/vizbuilder/app/pages/Visualize.jsx
packages/vizbuilder/app/pages/params.js
packages/vizbuilder/index.d.ts
packages/vizbuilder/src/components/ChartArea/index.jsx
packages/vizbuilder/src/components/ChartArea/style.css
packages/vizbuilder/src/components/PermalinkManager.jsx
packages/vizbuilder/src/components/Sidebar/index.jsx
packages/vizbuilder/src/helpers/chartConfig.js
packages/vizbuilder/src/helpers/chartCriteria.js
packages/vizbuilder/src/helpers/chartHelpers.js
packages/vizbuilder/src/helpers/formatting.js
packages/vizbuilder/src/helpers/loadstate.js
packages/vizbuilder/src/helpers/permalink.js
packages/vizbuilder/src/helpers/query.js
packages/vizbuilder/src/helpers/sorting.js
packages/vizbuilder/src/helpers/validation.js
packages/vizbuilder/src/index.js
packages/vizbuilder/src/state.js

closes #444
closes #447 
closes #455 
closes #461 
progresses on #462
about #462, the current state can sometimes generate duplicated charts

[vizbuilder] internal state model update

---

packages/vizbuilder/src/components/ChartArea/index.jsx
packages/vizbuilder/src/components/Sidebar/GroupingManager/GroupingItem.jsx
packages/vizbuilder/src/components/Sidebar/GroupingManager/index.jsx
packages/vizbuilder/src/components/Sidebar/MemberSelect.jsx
packages/vizbuilder/src/components/Sidebar/index.jsx
packages/vizbuilder/src/helpers/chartCollision.js
packages/vizbuilder/src/helpers/chartCriteria.js
packages/vizbuilder/src/helpers/chartHelpers.js
packages/vizbuilder/src/helpers/fetch.js
packages/vizbuilder/src/helpers/formatting.js
packages/vizbuilder/src/helpers/loadstate.js
packages/vizbuilder/src/helpers/permalink.js
packages/vizbuilder/src/helpers/query.js
packages/vizbuilder/src/helpers/sorting.js
packages/vizbuilder/src/index.js

closes #436 
closes #444 
discussion required on #448 
closes #453 
progresses on #462
closes #466

[vizbuilder] feb25/mar1 issues sprint

---

packages/vizbuilder/src/components/Sidebar/GroupingManager/GroupingItem.jsx
packages/vizbuilder/src/components/Sidebar/LevelDeepList.jsx
packages/vizbuilder/src/components/Sidebar/NewLevelSelect.jsx
packages/vizbuilder/src/components/Sidebar/VirtualList.jsx
packages/vizbuilder/src/components/Sidebar/index.jsx
packages/vizbuilder/src/components/Sidebar/select.css
packages/vizbuilder/src/helpers/chartConfig.js
packages/vizbuilder/src/helpers/fetch.js
packages/vizbuilder/src/helpers/formatting.js
packages/vizbuilder/src/helpers/loadstate.js
packages/vizbuilder/src/helpers/query.js

closes #455 
closes #475 
closes #479 
closes #480

[vizbuilder] mar4/mar8 issues sprint

---

packages/vizbuilder/app/pages/Map.jsx
packages/vizbuilder/app/pages/Visualize.jsx
packages/vizbuilder/app/pages/params.js
packages/vizbuilder/src/components/Sidebar/CustomSelect/BaseSelect.jsx
packages/vizbuilder/src/components/Sidebar/CustomSelect/MultiSelect.jsx
packages/vizbuilder/src/components/Sidebar/GroupingManager/GroupingItem.jsx
packages/vizbuilder/src/components/Sidebar/MemberDeepList.jsx
packages/vizbuilder/src/components/Sidebar/NewMemberSelect.jsx
packages/vizbuilder/src/components/Sidebar/select.css
packages/vizbuilder/src/helpers/chartConfig.js
packages/vizbuilder/src/helpers/chartCriteria.js
packages/vizbuilder/src/helpers/chartHelpers.js
packages/vizbuilder/src/helpers/formatting.js

closes #440 
closes #463 
closes #484 
closes #487

[vizbuilder] sprint mar11/mar15

---

packages/cms/package-lock.json
packages/cms/src/components/topics/Card.jsx

Re-orders stat divs in Card for https://github.com/Datawheel/cdc-pha/issues/798

Re-orders stat divs in Card

---

packages/vizbuilder/src/components/Sidebar/GroupingManager/index.jsx
packages/vizbuilder/src/components/Sidebar/index.jsx
packages/vizbuilder/src/helpers/fetch.js
packages/vizbuilder/src/helpers/query.js
packages/vizbuilder/src/helpers/sorting.js
packages/vizbuilder/src/index.js

closes #478 
closes #498 
closes #499 
closes #503

[vizbuilder] sprint mar28/mar29

---

packages/vizbuilder/src/components/Sidebar/GroupingManager/index.jsx
packages/vizbuilder/src/components/Sidebar/SidebarCRUDManager.jsx
packages/vizbuilder/src/components/Sidebar/index.jsx
packages/vizbuilder/src/components/Sidebar/style.css
packages/vizbuilder/src/index.css
packages/vizbuilder/src/index.js

[vizbuilder] sprint apr01-apr05

---

packages/vizbuilder/src/components/Sidebar/GroupingManager/index.jsx
packages/vizbuilder/src/components/Sidebar/SidebarCRUDManager.jsx
packages/vizbuilder/src/components/Sidebar/index.jsx
packages/vizbuilder/src/components/Sidebar/style.css
packages/vizbuilder/src/helpers/fetch.js
packages/vizbuilder/src/helpers/formatting.js
packages/vizbuilder/src/helpers/sorting.js
packages/vizbuilder/src/helpers/validation.js
packages/vizbuilder/src/index.js

[vizbuilder] updates Clear button to new behavior

---

packages/vizbuilder/src/helpers/chartCriteria.js
packages/vizbuilder/src/helpers/loadstate.js

[vizbuilder] resets activeChart state if more charts appear after a query

---

packages/cms/src/api/cmsRoute.js
packages/cms/src/api/mortarRoute.js

Closes #510 by refactoring routes to await

Refactors cms to await

---

packages/vizbuilder/package.json
packages/vizbuilder/src/components/Sidebar/index.jsx
packages/vizbuilder/src/helpers/query.js

adds grouping persistence between measures

---

packages/cms/src/components/Viz/Options.jsx
src/i18n/canon.js

related with Datawheel/data-estonia#46

includes missing translations to CMS

---

webpack/config/loaders.js

`.JPG` files are not currently supported.

Adds new url-loader file extension

---

packages/vizbuilder/src/helpers/chartConfig.js
packages/vizbuilder/src/helpers/errors.js
packages/vizbuilder/src/helpers/fetch.js
packages/vizbuilder/src/helpers/loadstate.js

[vizbuilder] no dataset warning and barchart axis formatting

---

packages/cms/src/components/cards/Card.jsx
packages/cms/src/components/cards/TextCard.jsx

Fixes a small bug in TextCard.jsx that caused edit button to disappear in certain scenarios

Fix title bug

---

packages/cms/src/components/editors/SimpleVisualizationEditor.jsx

adds title input to simpleviz editor

---

packages/cms/src/api/cmsRoute.js

Adds a simple slugify to search ingest.  Uses d3plus-text `strip` to create a slug, and appends the `id` of the resulting element if it is not unique.
Does not update slugs if they exist already.

adds slugify to search ingest

---

packages/vizbuilder/src/helpers/Filter.js
packages/vizbuilder/src/helpers/chartHelpers.js
packages/vizbuilder/src/helpers/query.js
packages/vizbuilder/src/index.d.ts

[vizbuilder] adds filter measures to chart tooltips

---

packages/cms/scripts/migration/canon-cms-migrate-0.6.js

Selectors used to be topic-based, now they are profile-wide. This can cause collision in namespacing. This improves the migration script to do two things:
- while moving selectors from topic to profile, append their name with the topic slug to make them unique.
- go through that topic's descriptions, vizes, etc. and replace all instances of `oldname` with `newname` (e.g., `year-select` will change to `year-select-this-topic-slug`). 
This is important because CDC for example has dozens of `year-select` selectors that all interfere with each other.

improves migration script to make selectors unique

---

packages/vizbuilder/src/helpers/chartHelpers.js

[vizbuilder/0.2] fixes bug on duplicate treemap detection

---

packages/vizbuilder/src/helpers/chartHelpers.js

[vizbuilder] fixes bug on duplicate treemap detection

---

.vscode/settings.json

This little PR includes file association for `css` as `scss` using Visual Studio Code.

includes SCSS association to CSS files in VSC

---

packages/vizbuilder/src/helpers/query.js

[vizbuilder] fixes bug generating queries with cuts

---

packages/vizbuilder/src/helpers/query.js

[vizbuilder/0.2] fixes bug generating queries with cuts

---

packages/vizbuilder/src/helpers/chartConfig.js
packages/vizbuilder/src/helpers/chartHelpers.js

fixes treemap labels
related to #611

[vizbuilder] removes treemap groupings with 1 member

---

packages/cms/package-lock.json
packages/cms/package.json
packages/cms/src/components/Viz/Options.jsx
packages/cms/src/components/Viz/Table.css
packages/cms/src/components/Viz/Table.jsx
packages/cms/src/components/fields/Button.jsx

tired: blueprint table
wired: react-table
one table library to rule them all
drop blueprint table
etc.
closes #629

Issue 629 table swap

---

app/App.css
app/components/Loading.css
packages/logiclayer/app/style.yml
webpack/config/loaders.js

Babel exclude and post css warnings

---

packages/vizbuilder/src/helpers/chartConfig.js
packages/vizbuilder/src/helpers/chartHelpers.js

fixes treemap labels
closes #611

[vizbuilder/0.2] removes treemap groupings with 1 member

---

packages/vizbuilder/src/helpers/chartConfig.js

[vizbuilder] adds label to x-axis on horizontal barcharts

---

packages/cms/src/components/sections/components/Parse.jsx
packages/cms/src/utils/formatters/stripOL.js
packages/cms/src/utils/formatters/stripUL.js

adds additional parsing (closes #649) (also needed for [CDC](https://github.com/DeloitteGeospatial/cdc-pha/pull/959))

parses lists, quotes, and pre tags

---

packages/cms/src/components/interface/SelectorUsage.jsx
packages/cms/src/components/sections/components/Selector.jsx

strips html from option rendering

---

packages/vizbuilder/src/helpers/formatting.js

adds Year measure formatter

---

packages/cms/src/api/cmsRoute.js
packages/cms/src/components/interface/SelectorUsage.jsx

Adds swap functionality to section selectors.
Closes #657

adds selector swap functionality

---

packages/cms/scripts/migration/canon-cms-migrate-0.6.js

fixes selector migration bug

---

packages/cms/src/components/sections/Default.jsx
packages/cms/src/components/sections/Grouping.jsx
packages/cms/src/components/sections/Hero.jsx
packages/cms/src/components/sections/InfoCard.jsx
packages/cms/src/components/sections/MultiColumn.jsx
packages/cms/src/components/sections/SingleColumn.jsx
packages/cms/src/components/sections/Tabs.jsx

Closes #681 .
Before merging, please get approval from @perpetualgrimace that this does not revert any behavior.

fixes bug with incorrect slugs

---

packages/vizbuilder/src/components/Sidebar/AllMeasureSelect.jsx
packages/vizbuilder/src/components/Sidebar/DatasetSelect.jsx
packages/vizbuilder/src/components/Sidebar/index.jsx
packages/vizbuilder/src/helpers/fetch.js
packages/vizbuilder/src/helpers/query.js
packages/vizbuilder/src/helpers/sorting.js

[vizbuilder] adds support for measure topics/subtopics

---

packages/vizbuilder/src/components/Sidebar/DatasetSelect.jsx
packages/vizbuilder/src/components/Sidebar/DeepList.jsx
packages/vizbuilder/src/components/Sidebar/MeasureSelect.jsx
packages/vizbuilder/src/components/Sidebar/NewMeasureSelect.jsx
packages/vizbuilder/src/components/Sidebar/index.jsx
packages/vizbuilder/src/helpers/fetch.js
packages/vizbuilder/src/helpers/query.js
packages/vizbuilder/src/helpers/sorting.js

[vizbuilder/v0.2] adds support for measure topics/subtopics

---

packages/cms/app/style.yml
packages/cms/src/components/Viz/PercentageBar.css
packages/cms/src/components/Viz/PercentageBar.jsx

Added SVG ticks and labels to PercentageBar. Added isPercentValue boolean parameter to determine type of labels to display.

PercentageBar Updates

---

packages/cms/src/components/sections/Grouping.css
packages/cms/src/components/sections/Section.css
packages/cms/src/components/sections/Section.jsx
packages/cms/src/components/sections/components/Parse.jsx

adds tabindex & links to profile section headings

---

packages/cms/src/components/Viz/Graphic.css
packages/cms/src/components/Viz/Graphic.jsx
packages/cms/src/components/Viz/Viz.jsx
packages/cms/src/components/cards/Card.jsx
packages/cms/src/components/editors/GeneratorEditor.jsx
packages/cms/src/components/editors/SimpleVisualizationEditor.jsx
packages/cms/src/components/sections/Default.jsx
packages/cms/src/components/sections/Grouping.jsx
packages/cms/src/components/sections/Hero.jsx
packages/cms/src/components/sections/Section.css
packages/cms/src/components/sections/Tabs.jsx
packages/cms/src/components/variables/DefinitionList.jsx
packages/cms/src/css/base.css
packages/cms/src/css/form-fields.css
packages/cms/src/utils/formatters/stripEntities.js

- closes #694 
- also closes #721
- also fixes a bug from #715

694 graphic viz

---

packages/cms/src/Builder.jsx
packages/cms/src/member/MetaEditor.jsx
packages/cms/src/profile/ProfileBuilder.jsx
packages/cms/src/story/StoryBuilder.jsx

A 🎁 for @perpetualgrimace 
Adds full pathing (including preview ids) to Profiles and Stories.  Urls look like:
`/?tab=profiles&profile=13&section=22&previews=VAE,6`
`/?tab=stories&story=1&storysection=1`
`/?tab=metadata`
Closes #702

Improve permalinks

---

packages/vizbuilder/package-lock.json
packages/vizbuilder/src/components/ChartArea/index.jsx
packages/vizbuilder/src/components/Sidebar/ConditionPropertySelect.jsx
packages/vizbuilder/src/components/Sidebar/CustomSelect/MonoSelect.jsx
packages/vizbuilder/src/components/Sidebar/DeepList.jsx
packages/vizbuilder/src/components/Sidebar/FilterManager/Filter.js
packages/vizbuilder/src/components/Sidebar/GroupingManager/Grouping.js
packages/vizbuilder/src/components/Sidebar/GroupingManager/GroupingItem.jsx
packages/vizbuilder/src/components/Sidebar/LevelDeepList.jsx
packages/vizbuilder/src/components/Sidebar/LevelSelect.jsx
packages/vizbuilder/src/components/Sidebar/MeasureSelect.jsx
packages/vizbuilder/src/components/Sidebar/MemberDeepList.jsx
packages/vizbuilder/src/components/Sidebar/MemberSelect.jsx
packages/vizbuilder/src/components/Sidebar/MultiLevelSelect/index.jsx
packages/vizbuilder/src/components/Sidebar/NewLevelSelect.jsx
packages/vizbuilder/src/components/Sidebar/NewMeasureSelect.jsx
packages/vizbuilder/src/components/Sidebar/NewMemberSelect.jsx
packages/vizbuilder/src/components/Sidebar/Ranking.jsx
packages/vizbuilder/src/helpers/chartConfig.js
packages/vizbuilder/src/helpers/chartCriteria.js
packages/vizbuilder/src/helpers/chartHelpers.js
packages/vizbuilder/src/helpers/fetch.js
packages/vizbuilder/src/helpers/formatting.js
packages/vizbuilder/src/helpers/sorting.js

[vizbuilder/v0.2] updates labels to use caption property

---

packages/cms/src/Builder.jsx
packages/cms/src/components/interface/AuthForm.jsx

Fixes bug discovered by @cnavarreteliz that caused CMS Logins to redirect to `/` instead of the custom cms route.

fixes redirect bug on auth submit

---

packages/cms/src/components/sections/Section.css

removes anchor link offset from sticky section titles

---

packages/cms/src/Builder.jsx
packages/cms/src/components/Profile.jsx
packages/cms/src/components/Viz/Options.css
packages/cms/src/components/Viz/Table.css
packages/cms/src/components/fields/Search.css
packages/cms/src/components/interface/Deck.css
packages/cms/src/components/interface/Toolbox.css
packages/cms/src/components/interface/Toolbox.jsx
packages/cms/src/components/sections/Section.css
packages/cms/src/components/sections/Section.jsx
packages/cms/src/components/variables/ConsoleVariable.css
packages/cms/src/css/blueprint-overrides.css
packages/cms/src/css/layout.css
packages/cms/src/css/mixins.css
packages/cms/src/css/utilities.css
packages/cms/src/member/MetaEditor.css
packages/cms/src/profile/ProfileBuilder.jsx

Went in with the goal of adding a button that hides/shows the toolbox, wound up also refactoring/rewriting/reorganizing most of the layout styles. 😅
But it feels much smoother now, and will make my life easier when it's time to start implementing #725.

717 collapsible toolbox

---

packages/vizbuilder/src/helpers/chartHelpers.js

[vizbuilder/v0.2] fixes missing map in geo + unique cut queries

---

packages/vizbuilder/src/helpers/chartHelpers.js

[vizbuilder/v0.3] fixes missing map in geo + unique cut queries

---

packages/cms/README.md

Issue 772 docs

---

packages/cms/src/components/Profile.jsx

Without a Hero, modals weren't hiding.

makes modals hide properly

---

packages/cms/src/components/Profile.jsx
packages/cms/src/components/Viz/Viz.jsx
packages/cms/src/components/cards/VisualizationCard.jsx
packages/cms/src/components/fields/Button.jsx
packages/cms/src/components/sections/Default.jsx
packages/cms/src/components/sections/Grouping.jsx
packages/cms/src/components/sections/InfoCard.css
packages/cms/src/components/sections/InfoCard.jsx
packages/cms/src/components/sections/MultiColumn.jsx
packages/cms/src/components/sections/Section.css
packages/cms/src/components/sections/Section.jsx
packages/cms/src/components/sections/SingleColumn.jsx
packages/cms/src/components/sections/Tabs.jsx

styles var reset button

---

packages/cms/src/Builder.jsx

sets default secondary language to none

---

packages/cms/src/components/cards/SelectorCard.jsx
packages/cms/src/components/interface/Toolbox.jsx

part of #793 
Also fixes bug with deleting selectors.

auto-opens selectors and formatters on creation

---

packages/cms/api/testRoute.js
packages/cms/src/components/editors/SimpleVisualizationEditor.jsx

adds more robust payload extractor for simpleviz

---

packages/cms/src/api/imageRoute.js

fixes bug in metaeditor that hid images

---

packages/cms/src/components/editors/SelectorEditor.jsx

fixes issue with deleted default selectors

---

packages/cms/src/components/sections/Grouping.css
packages/cms/src/components/sections/Section.css

fixes minor visual bugs with Grouping sections

---

packages/cms/src/api/searchRoute.js

adds catch for image failure in flickr

---

packages/cms/src/member/MetaEditor.jsx

adds id to metacolumn

---

packages/cms/src/components/cards/DimensionCard.jsx
packages/cms/src/components/fields/PreviewSearch.css
packages/cms/src/components/fields/PreviewSearch.jsx

makes preview search fully functional via keyboard

---

packages/cms/src/components/cards/GeneratorCard.jsx

fixes bug with dupes in attribute generator

---

packages/cms/src/member/MetaEditor.jsx

handles duplicates in meta editor

---

packages/cms/src/components/cards/Card.jsx
packages/cms/src/components/cards/SelectorCard.jsx
packages/cms/src/components/cards/VariableCard.jsx
packages/cms/src/components/interface/Alert.jsx
packages/cms/src/components/interface/Toolbox.jsx

Issue 878 alert z index bug

---

packages/cms/src/components/interface/Outline.css
packages/cms/src/components/interface/Outline.jsx

Hopefully improves [this situation](https://datawheel.slack.com/archives/C6D91RL4B/p1576684060020900)

handles images in outline titles

---

packages/cms/src/components/sections/SingleColumn.css

pushes visualizations to the bottom in single column sections

---

packages/cms/src/components/Viz/PercentageBar.jsx
packages/cms/src/components/Viz/Table.jsx
packages/cms/src/components/Viz/Viz.jsx

fixes bug found by gilberto which caused whitescreens in custom vizes when `data` was not provided in config

fixes whitescreen bug with tables

---

packages/cms/src/member/MetaEditor.jsx

adds loading text to MetaEditor table

---

packages/cms/src/components/editors/VariableEditor.css
packages/cms/src/components/editors/VariableEditor.jsx
packages/cms/src/css/mixins.css
packages/cms/src/member/MetaEditor.css

I'm using what I assume to be the correctly compiled URL from one of Jimmy's functions here. Should be good, but please test before releasing.
closes #729

prints compiled generator url in editor after fetch

---

packages/cms/app/routes.jsx
packages/cms/src/api/imageRoute.js
packages/cms/src/components/fields/ProfileSearch.jsx
packages/cms/src/components/fields/ProfileTile.jsx
packages/cms/src/components/interface/Header.jsx
packages/cms/src/utils/linkify.js

Fix linkify regex

---

packages/cms/src/components/ProfileRenderer.jsx
packages/cms/src/components/fields/Button.css
packages/cms/src/components/fields/ButtonGroup.css
packages/cms/src/components/fields/ButtonGroup.jsx
packages/cms/src/components/fields/Select.jsx
packages/cms/src/components/sections/components/Selector.jsx
packages/cms/src/components/sections/components/Subnav.jsx

I think I implemented this correctly, but please test before releasing.
closes #604

604 selectors as button groups

---

packages/cms/README.md
packages/cms/src/Builder.jsx
packages/cms/src/api/cmsRoute.js

Adds `CANON_CMS_MINIMUM_ROLE` and documentation for configuration.
closes #908

Issue 908 login config

---

packages/cms/src/api/searchRoute.js

Updates search endpoint to respect cubenames.
Closes #921

Issue 921 search updates

---

packages/cms/src/utils/funcifyFormatterByLocale.js

wraps funcify in try catch

---

packages/cms/README.md
packages/cms/src/components/Viz/HTML.jsx
packages/cms/src/components/Viz/Table.jsx
packages/cms/src/components/Viz/Viz.jsx
packages/cms/src/components/editors/VisualizationEditorUI.jsx
packages/cms/src/components/editors/vizLookup.js
packages/cms/src/components/editors/vizMethods.js
packages/cms/src/components/interface/HTML.jsx
packages/cms/src/components/interface/Navbar.jsx

Adds HTML Viztype to cms visualizations configurable via simple UI.  Also adds docs.
@davelandry Please take over the `issue-922` branch and style it on the front end!

[cms] Issue 922 html viztype

---

packages/cms/src/components/editors/VariableEditor.jsx

fixes a naming issue that was hiding the allowed option in vizes

adds allowed back into vizes

---

packages/cms/src/components/cards/TextCard.jsx
packages/cms/src/components/sections/components/Subnav.jsx

fixes hidden section titles

---

packages/cms/src/api/mortarRoute.js

Fixes bug where name attribute did not show on front-end profiles

Fix name frontend

---

packages/cms/src/api/mortarRoute.js
packages/cms/src/api/searchRoute.js
packages/cms/src/utils/attify.js

adds cubename to magic generator

---

packages/cms/README.md
packages/cms/src/api/mortarRoute.js

adds slug injector and documentation

---

packages/cms/src/api/imageRoute.js
packages/cms/src/api/mortarRoute.js
packages/cms/src/api/searchRoute.js
packages/cms/src/components/fields/ProfileSearch.jsx
packages/cms/src/components/sections/Hero.css
packages/cms/src/components/sections/Hero.jsx
packages/cms/src/components/sections/components/Parse.jsx
packages/cms/src/utils/populateSearch.js

Closes #952 
Overloads the ProfileSearch component to receive a formatting callback, so it may be used for single-dimension searches.
@davelandry Can you please test and design-pass this before merging?

Issue 952 titlesearch

---

packages/cms/src/components/cards/VariableCard.jsx

adds size warning to generators

---

packages/cms/src/api/mortarRoute.js

catches for when generatorsfail to return an object

---

packages/cms/src/components/ProfileRenderer.jsx

fixes bug that voided logins on clicking links

---

packages/cms/src/api/mortarRoute.js

The :neighbors endpoint will no longer erroneously provide `{show: false}` members.
Closes #964

Issue 964 neighbor filters

---

packages/cms/src/api/mortarRoute.js
packages/cms/src/components/Profile.css
packages/cms/src/components/Profile.jsx

Adds a 404 return to profile route.
Still waiting on a designed 404 component from @davelandry.
Closes #425

adds 404s to profile route

---

packages/cms/src/Builder.jsx
packages/cms/src/components/interface/Header.jsx
packages/cms/src/profile/ProfileBuilder.jsx

[cms] adds alert before leaving page

---

packages/cms/src/components/Viz/Options.jsx

fixes bug where manual data showed in endpoints

---

packages/cms/src/api/mortarRoute.js
packages/cms/src/api/searchRoute.js
packages/cms/src/components/fields/PreviewSearch.jsx

removes self-referencing neighbors, fixes show:false in search results

---

packages/cms/src/api/mortarRoute.js
packages/cms/src/utils/varSwapRecursive.js

This PR closes #998 and makes two important performance changes.
Firstly, a `reduce` operation for dynamic selectors was slowing down varSwap substantially, moving the calculation outside of the loop improved performance greatly.
Secondly, and perhaps more controversially - on larger profiles, simply doing the profile GET operation in sequelize was taking up to 1.5 seconds, due to the huge nested includes in the profile tree. 
I now send the entire raw profile down the wire on first load in a `_rawProfile` key in the `variables` object. On subsequent `POST` operations which use `variables`, I simply re-use that `_rawProfile` instead of doing the bulky GET, which can save 1.5 seconds from load times (though we lose some time in the bulkier POST). 
I am researching whether the entire POST …

Issue 998 performance

---

packages/cms/src/actions/profiles.js
packages/cms/src/components/sections/components/Selector.jsx

- Fixes bug that was injecting a faulty user object when CANON_LOGINS was false or unset
- Fixes a rendering bug for multi-selects

[cms] cdc fixes

---

src/actions/auth.js
src/auth/auth.js

more graceful response in isAuthenticated issue #1008

---

packages/cms/src/utils/selectors/validateDynamic.js

[cms] adds catch against malformed allowed in dynamic selectors

---

packages/cms/src/api/mortarRoute.js

[cms] fixes two lookup bugs with slugs and cubename uniqueness

---

packages/cms/package-lock.json
packages/cms/src/components/cards/VariableCard.jsx
packages/cms/src/components/interface/Toolbox.css
packages/cms/src/components/interface/Toolbox.jsx
packages/cms/src/components/variables/ConsoleVariable.jsx
packages/cms/src/components/variables/VarTable.css
packages/cms/src/components/variables/VarTable.jsx

[cms] hides variables in display windows to improve performance

---

packages/cms/src/reducers/status.js

Fixes a bug in CDC that prevented story updates from registering the "saved" notification.

fixes omitted status routes for CRUD story operations

---

packages/cms/src/api/mortarRoute.js
packages/cms/src/components/ProfileRenderer.jsx

adds token auth to neighbors, hides if empty

---

packages/cms/README.md
packages/cms/src/utils/linkify.js

adds disambiguation and docs for routes

---

packages/cms/src/components/cards/VariableCard.jsx
packages/cms/src/reducers/status.js

fixes bug in output view

---

examples/api/cmsTestRoute.js
packages/cms/src/components/Viz/Options.jsx

closes #1026 .
Also adds in some testing cms routes for the example app.

Issue 1026 urlbug

---

packages/cms/src/api/mortarRoute.js

The issue described in #1052 is not the actual issue - in fact, groupings just weren't yet designed to propagate down to their children.
I've added that in this PR. Note that I only propagate the `allowed` down to its child sections **if the grouping's `allowed` is falsey**. This means that an otherwise visible/allowed grouping may have its children be allowed or not allowed as they see fit (unconstrained by the parent).
closes #1052

makes groupings cascade their false-y alloweds to children.

---

packages/cms/src/components/Viz/Viz.jsx

[cms] fixes sources for mult data vizes

---

packages/cms/package.json
packages/cms/scripts/warmup/cliScan.js
packages/cms/scripts/warmup/consts.js
packages/cms/scripts/warmup/index.js
packages/cms/scripts/warmup/logger.js
packages/cms/scripts/warmup/models.js
packages/cms/scripts/warmup/request.js
packages/cms/scripts/warmup/workerPool.js

Very early beta.
Run `npx canon-cms-warmup --help` for information.

[cms] warmup script

---

packages/cms/src/api/searchRoute.js

- Same unaccent support to `search` and `profilesearch`
- Fallback if is not installed.

add unaccent function to regular search query 

---

packages/cms/scripts/warmup/cliRetry.js
packages/cms/scripts/warmup/cliRun.js
packages/cms/scripts/warmup/index.js
packages/cms/scripts/warmup/request.js
packages/cms/scripts/warmup/workerPool.js

* improves progress view
* fixes auth parameters
* adds new parameter: `--output, -o <filename>` : logs errors into that file in jsonlog format

cms-warmup script improvements

---

packages/cms/src/components/sections/components/Selector.jsx

Fixes a bug where multiselects were hiding their "add comparison" button when they are down to zero comparisons.

fixes bug in multi-selectors that hid on no defaults

---

examples/app/pages/Docs.jsx
examples/app/pages/core/Links.jsx
packages/core/src/CanonProvider.jsx

See: https://github.com/Datawheel/oec-site/issues/4
Fixed #1081

Add missing hash to anchor redirect

---

packages/cms/src/api/searchRoute.js

[cms] Adds attr to search payload

---

packages/cms/src/member/MetaEditor.jsx

Fix keyword inputs

---

packages/cms/src/components/sections/Hero.jsx

handles lt/gt signs in titles

---

examples/api/proxy.js
packages/cms/src/api/mortarRoute.js

adds slugfix for relative paths and adds olap proxy to dev env

---

packages/cms/README.md
packages/cms/src/api/mortarRoute.js

fixes slug disambiguation with third arg

---

examples/package.json
packages/cms/package.json
packages/cms/src/components/cards/Card.css
packages/cms/src/components/editors/VisualizationEditorUI.jsx
packages/cms/src/components/editors/components/VizRow.jsx
packages/cms/src/components/editors/vizLookup.js
packages/cms/src/components/editors/vizMethods.js
packages/logiclayer/package.json
packages/vizbuilder/package.json
pnpm-lock.yaml

- Updates d3plus-react to include new Matrix and RadialMatrix chart types
- Adds simple-viz hooks for Matrix and RadialMatrix
- Refactors simple-viz HTML logic to be more flexible/generic
- Adds optional colorScale to more simple-viz configs
- Adds some default colorScale and axis title label behavior
- Closes #1119

[cms] simple-viz updates and transparency bug

---

examples/app/routes.jsx
packages/cms/src/components/fields/ProfileSearch.jsx

uses i18n to infer locale for profilesearch component.

fixes profilesearch locale

---

packages/cms/src/api/searchRoute.js

allows search by id

---

packages/cms/src/utils/populateSearch.js

protects against dupe ids in tess

---

packages/cms/package.json
packages/cms/src/api/searchRoute.js
packages/cms/src/components/sections/Hero.jsx
packages/cms/src/member/MetaEditor.jsx
pnpm-lock.yaml

Adds ability to upload custom images to CMS
Closes #1155

Issue 1155 image upload

---

packages/cms/src/api/cmsRoute.js
packages/cms/src/components/cards/DimensionCard.jsx
packages/cms/src/utils/populateSearch.js

adds slug reingest

---

packages/cms/src/api/cmsRoute.js
packages/cms/src/components/cards/DimensionCard.jsx
packages/cms/src/components/editors/DimensionEditor.jsx
packages/cms/src/utils/populateSearch.js
pnpm-lock.yaml

Issue 1175 ciren ingest

---

packages/cms/README.md
packages/cms/src/api/imageRoute.js
packages/cms/src/api/mortarRoute.js
packages/cms/src/components/sections/Hero.jsx
packages/cms/src/member/MetaEditor.jsx

Issue 1180 images

---

packages/cms/package.json
pnpm-lock.yaml

upgrades puppeteer and sharp

---

packages/cms/src/components/sections/components/Subnav.jsx
packages/core/src/client.jsx

* refactors scrollTo logic to retry as content loads
* decreases scrollToHash retry timeout and animation durations
* fixes bug with Subnav not using nav and subnav heights

[core/cms] anchor scroll and subnav behavior

---

examples/app/routes.jsx
packages/cms/src/api/imageRoute.js
packages/cms/src/api/mortarRoute.js
packages/cms/src/components/StoryLanding.jsx
packages/cms/src/components/cards/TextCard.jsx
packages/cms/src/components/editors/PlainTextEditor.css
packages/cms/src/components/editors/PlainTextEditor.jsx
packages/cms/src/components/sections/Hero.jsx
packages/cms/src/story/StoryEditor.jsx

Fixes story editors and basic story profile.
Fixes bug with images not being able to use slugs

fixes story plainfields, fixes image linking

---

packages/cms/README.md
packages/cms/src/api/pdfRoute.js
packages/cms/src/db/profile_meta.js

adds slug/memberslug verification to pdf route
Also adds `CANON_CMS_PDF_DISABLE` to unhook endpoints entirely.
closes #1210

Issue 1210 pdf secure

---

packages/cms/src/components/editors/AceTheme.css
packages/cms/src/components/sections/components/Subnav.jsx

[cms] fixes ace punctuation colors and subnav error

---

packages/cms/src/components/ProfileRenderer.jsx
packages/cms/src/components/sections/Hero.jsx
packages/core/src/i18n/canon.js

adds translation to hero

---

packages/reports/README.md
packages/reports/scripts/migration/canon-cms-migrate-0.20.js
packages/reports/scripts/migration/migrationUtils.js
packages/reports/src/api/builderRoute.js
packages/reports/src/api/imageRoute.js
packages/reports/src/api/ingestRoute.js
packages/reports/src/api/pdfRoute.js
packages/reports/src/api/searchRoute.js
packages/reports/src/api/translateRoute.js
packages/reports/src/utils/blocks/runConsumers.js
packages/reports/src/utils/translation/translateContent.js
packages/reports/src/utils/translation/translateText.js
packages/reports/src/utils/translation/translationUtils.js
packages/reports/src/utils/variables/mortarEval.js

Change all `CANON_CMS_XXXXX` vars to `CANON_REPORTS_XXXXX`.
closes #1294

1294 Change env namespace

---

packages/reports/src/reports/blocks/Block.jsx
packages/reports/src/reports/blocks/BlockOutputPanel.jsx
packages/reports/src/reports/editors/SimpleUI.jsx
packages/reports/src/reports/editors/simple/SelectorUI.css
packages/reports/src/reports/editors/simple/SelectorUI.jsx

Added Simple UI for creating a STATIC (aka non-dynamic) selector.

Simple UI Static Selector

---

.dockerignore
.github/workflows/gcp-build-deploy.yml
Dockerfile

Add:
- Dockerfile and .dockerignore for building the docker image
- .github/workflow for the github actions workflow for building and deploying the app on google cloud

Cms 1.0 develop actions workflows

---

package-lock.json
packages/next/cms/components/ProfileRenderer.js
packages/next/cms/components/Viz/Options.js
packages/next/cms/components/Viz/Viz.js
packages/next/cms/components/fields/ProfileSearch.js
packages/next/cms/components/fields/ProfileTile.js
packages/next/cms/components/sections/Section.js
packages/next/core/components/NonIdealState.js
packages/next/index.ts
packages/next/package.json

Small fixes to package.json and imports.
Also fixes NonIdealState

Canon next 0.1.2

---

example-next/next.config.js
example-next/pages/index.js
package-lock.json
package.json
packages/next/.eslintignore
packages/next/.eslintrc.json
packages/next/cms/components/Profile.js
packages/next/cms/components/ProfileContext.js
packages/next/cms/components/ProfileRenderer.js
packages/next/cms/components/Viz/Options.js
packages/next/cms/components/Viz/StatGroup.js
packages/next/cms/components/Viz/Viz.js
packages/next/cms/components/fields/ProfileSearch.js
packages/next/cms/components/sections/Section.js
packages/next/cms/components/sections/components/Stat.js
packages/next/cms/components/sections/components/Subnav.js
packages/next/cms/hooks/use-on-set-variables.js
packages/next/cms/hooks/use-report-state.js
packages/next/cms/hooks/use-role-protected.js
packages/next/core/components/NonIdealState.js
packages/next/index.js
packages/next/package.json
packages/next/tsup.config.js

@davelandry I made a bunch of releases for the oec while you were out. Mostly bugfixes. Here's a summary:
0.2.6: Fixes node conflict.
0.2.7: Fixes comparison sections.
0.2.8: Fixes profile search errors.
0.2.9: Adds user's to renderer.
0.2.10: Fixes re-rendering issues and other small bugs on subnav. Adds a linter config.

Canon next 0.2.7

---

packages/next/cms/components/Viz/Viz.js

**Changelog:**
- removed d3plus overrides related to shapeConfig defined in the Viz component

remove shapeConfig override
